### ISSUE TITLE
Prisma Studio not Evaluating env Variable before Opening SQLite DB 

### ISSUE THREAD

**Issue by HunterHeston** [prisma/studio#599] opened 2020-12-25 00:46 UTC
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
@prisma/cli          : 2.13.1
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

2. Logs from Developer Tools Console or Command line, if any:
```
Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `file:`.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `file:`.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/sdk/dist/engineCommands.js:183:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/studio-pcw/build/pcw.js:25:53)\n    at async IpcMainImpl.photon (/Applications/Prisma Studio.app/Contents/Resources/app/build/ipc/photon-ipc.js:32:63)"
}
Error: Error starting Prisma Client: {
  "message": "Schema Parsing P1012\n\nGet config \nerror: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `file:`.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1\n",
  "stack": "Error: Schema Parsing P1012\n\nGet config \nerror: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `file:`.\n  -->  schema.prisma:3\n   | \n 2 |   provider = \"sqlite\"\n 3 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1\n\n    at Object.getConfig (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/sdk/dist/engineCommands.js:183:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Photon.generate (/Applications/Prisma Studio.app/Contents/Resources/app/node_modules/@prisma/studio-pcw/build/pcw.js:25:53)\n    at async IpcMainImpl.photon (/Applications/Prisma Studio.app/Contents/Resources/app/build/ipc/photon-ipc.js:32:63)"
}
    at ir.init (file:///Applications/Prisma%20Studio.app/Contents/Resources/app/renderer/mainChunk.js:395:160254)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
This was an issue opening the Prisma schema using Prisma Studio.
Prisma Studio Version: `0.330.0 (0.330.0)`

4. Prisma schema (if relevant):
```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

```

5. .env file
```
DATABASE_URL="file:./dev.db"
```

6. I was able to resolve this by hardcoding: `"file:./dev.db"` into my prisma.schema

**Comment by madebysid** [comment] 2020-12-25 09:34
Hey @HunterHeston, thanks for reporting this!

Couple of questions:
1. Where are you placing your .ENV file?
2. Are you able to get Prisma Client to work with environment variables? Is it only Studio that's broken?

We use the same logic in both places, so this is not expected.

**Comment by HunterHeston** [comment] 2020-12-25 15:00
@madebysid I'll verify today/tomorrow and comment.

**Comment by HunterHeston** [comment] 2020-12-27 02:46
@madebysid I had 2 `.env` files. One at the project root level and one nested inside of the Prisma directory. 

Both of them had DATABASE_URL variables defined. Root level `.env` pointed to a non-existent Postgres database. Prisma level file pointed to the sqlite file. 

I am able to successfully add and retrieve values from the SQLite database with `DATABASE_URL="file:./dev.db"` place in either file. 

Moving this value to the root level `.env` file got Prisma studio working. I then moved the `DATABASE_URL` variable back and forth between both `.env` files and Prisma studio no longer seemed to care. I also removed the variable altogether and it still opened successfully. 

Moving forward with a single `.env` file at my project root level.

**Comment by madebysid** [comment] 2021-01-11 13:21
Hey! Apologies for the delay, I was out for a couple of weeks.

It is super strange that moving your `.env` file around once fixed it for all other cases.

I tried doing what you did, but I can't seem to reproduce this. I started out with the `.env` file in the `prisma` folder, and ran `npx prisma studio`, which seemed to resolve my env var correctly, then moving it to the root did the same.

Are you still able to see this consistently?
Studio generates its own Prisma Client in `~/.cache/prisma/studio/{projectHash}` or `%APPDATA%\Prisma\Studio\{projectHash}`, so you muight want to clear this folder out, although it shouldn't be necessary, Studio does that for you on startup. I'm just trying to figure out what happened here to make sure there isn't someting sketchy going on.

Let me know if I misunderstood your setup though!

**Comment by gaurangrshah** [comment] 2021-02-01 19:30
Hey guys I'm having the same issue,

`package.json`
`
  "dependencies": {
    "@prisma/client": "^2.15.0",
  },
  "devDependencies": {
    "@prisma/cli": "^2.15.0"
  }
`

`schema.prisma`
`
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
`

`.env` -- located at the root of the project 
`DATABASE_URL="file:./dev.db"`

I can confirm that the client is working as expected, but for some reason, prisma/studio is not picking up the variable which the client seems to be doing just fine. 

Also verified that the data is populating in the database as well, just to confirm. 
![image](https://user-images.githubusercontent.com/1086269/106507661-5e4fe400-6499-11eb-89c8-4e8d6682cb22.png)

**ALSO NOTE**  the issue seems to occur when using sqlite, I tested with a postgres db and both client and studio worked smoothly. 

I just pushed up a repo, in case someone wants to give that a shot:
https://github.com/gaurangrshah/next-prisma-auth

**Comment by gaurangrshah** [comment] 2021-02-02 20:38
Just as an FYI the issue has seemed to resolve itself. Not sure if it was something I've done since or just one of those one off things.

**Comment by Craytor** [comment] 2021-02-28 19:09
I just experienced a similar issue but working with a postgresql db. I had to manually force close the Prisma Studio app and reopen which it then was able to use my updated `DATABASE_URL` environment variable. Before I was just closing out of the dataviewer and going reopening through the schema selector. It seemed the force restart fixed it, but I think it just needs to check to see if env variables have changed if it does not successfully connect to the db.

**Comment by madebysid** [comment] 2021-03-01 09:57
@Craytor IIUC that's to be expected. It's weird, but currently Studio only resolves env vars once in the begining. On `npx prisma studio`, it does this when you start the process, and on the electron app, it does so when you open a project.

I haven't been able to reproduce this BTW, and issues seem to resolve themselves :sweat_smile: , which is worrying. Studio does use the same logic for resolving env vars as Prisma Client itself, so if this is happening consistently for anyone, it'd be great if you can isolate it with Client (might be easier to re-produce there)

**Comment by Mozart409** [comment] 2021-04-17 12:18
HI, im using the following prisma versions 

```sh
yarn run v1.22.5
$ /home/amadeus/GitHub/blitz-carty/node_modules/.bin/prisma -v
Environment variables loaded from .env
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
✨  Done in 1.36s.

```

My ".env" file is being loaded, and I can confirm that this works, but using another .env file like ".env.local" or ".env.development" does not work. 

Is there a fix in sight?

**Comment by madebysid** [comment] 2021-04-22 12:32
@Mozart409 Is your issue specific to Studio or does it happen with all Prisma stuff? If it isn't Studio-specific, it'll be best to create an issue on https://github.com/prisma/prisma

**Comment by Mozart409** [comment] 2021-04-22 13:08
@madebysid hi,
only Studio. All other stuff works.

**Comment by Albert-Gao** [comment] 2021-05-26 03:15
1. how to set env for standalone app?
2. also, we do not use `.env`, we just use a `.sh` to export all the env vars, we are doing something like `source ./env/dev.sh && npx prisma studio`, it is not working, do not know if it is an issue, but the error is weird

<img width="323" alt="image" src="https://user-images.githubusercontent.com/18282328/119597468-2ea45d80-be35-11eb-9cff-fa85cb806c3a.png">

**Comment by madebysid** [comment] 2021-05-27 11:02
The electron app resolves env vars the same way as the CLI, you shouldn't need extra setup. If you place your `.env` file next to your schema (or wherever else it works with Prisma CLI), then the app should pick it up as well.

In your case @Albert-Gao, since you don't use `.env`s, I think this might be a little harder to accomplish since there's no way to add env vars to the app directly unfortunately. Depending on your OS, you can run the executable directly, with your env vars exported (on macOS, for example, you can do: `source ./env/dev.sh && ~/Applications/Prisma\ Studio/Contents/MacOS/Prisma\ Studio`). I think in your case, I'd just recommend you use the CLI instead.

I will take a look at this issue (and env var resolution in general) soon.

**Closed** 2024-06-07 22:08 UTC
Labels: bug/0-unknown, kind/bug
