### ISSUE TITLE
Error in Studio

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/studio#331] opened 2020-01-12 06:55 UTC
**Error dump**
Cannot read property 'isScript' of null

**Stacktrace**
TypeError: Cannot read property 'isScript' of null
    at http://localhost:5555/studioBundle.js:87:71386
    at Array.forEach (<anonymous>)
    at http://localhost:5555/studioBundle.js:87:71364
    at Set.forEach (<anonymous>)
    at Vi.update (http://localhost:5555/studioBundle.js:87:71222)
    at $ (http://localhost:5555/studioBundle.js:16:6357)
    at Vi.i (http://localhost:5555/studioBundle.js:16:6129)
    at Ki.init (http://localhost:5555/studioBundle.js:87:73459)

**Comment by madebysid** [comment] 2020-01-13 09:41
Hey @malekjaroslav, could you perhaps show me a way to reproduce this? Does this happen as soon as you open Studio, or are there specific things I can do to reproduce this?

**Comment by madebysid** [comment] 2020-02-07 13:35
Closing since I haven't been able to reproduce this on alpha. Please reopen if you're still running into this!

**Closed by madebysid** 2020-02-07 13:35 UTC
Labels: bug/0-needs-info, kind/bug
