### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by renay007** [prisma/studio#1076] opened 2023-01-08 20:24 UTC
### Bug description

 A non-recoverable error has occurred. Reload Studio to continue. Consider reporting this error to us by opening an issue on GitHub and attaching the error details.

Unable to process `count` query
undefined

### How to reproduce

1. Go to [Data Browser](https://cloud.prisma.io/renay007/grey-horse-ndfqtfbbwc/production/databrowser)
2. See error

### Prisma information

```
model Post {
  id        Int      @id @default(autoincrement())
  authorId  Int?
  title     String
  views     Int?     @default(1)
  published Boolean? @default(false)
  createdAt DateTime @default(now())
  updatedAt DateTime
  User      User?    @relation(fields: [authorId], references: [id])

  @@index([authorId], map: "Post_authorId_fkey")
}

model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  fullname  String?
  createdAt DateTime @default(now())
  Post      Post[]
}

```

### Environment & setup

- Link to Data Browser instance: https://cloud.prisma.io/renay007/grey-horse-ndfqtfbbwc/production/databrowser
- OS:  Mac OS
- Browser: Safari
- Database: MySQL

**Comment by petradonka** [comment] 2023-01-11 08:35
Thanks for reporting the error! It looks like it is a duplicate of https://github.com/prisma/studio/issues/890.

**Closed by petradonka** 2023-01-11 08:35 UTC
Labels: kind/bug
