### ISSUE TITLE
filter not working

### ISSUE THREAD

**Issue by chrissisura** [prisma/studio#611] opened 2021-01-21 09:48 UTC
1. Prisma version (`prisma -v` or `npx prisma -v`):
prisma studio 0.340.0
2. Logs from Developer Tools Console or Command line, if any:
```
Message: Error in Prisma Client request: 

Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42883"), message: "function lower(uuid) does not exist", detail: None, hint: Some("No function matches the given name and argument types. You might need to add explicit type casts."), position: Some(Original(203)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_func.c"), line: Some(627), routine: Some("ParseFuncOrColumn") }) }) })
    at PrismaClientFetcher.request (/Users/chrissisura/Library/Application Support/@prisma/studio-electron/projects/fdf2f9ad/runtime/index.js:78459:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/build/pcw.js:139:35
    at async /Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/build/pcw.js:112:32
    at async Photon.request (/Applications/Prisma Studio.app/Contents/Resources/app.asar/node_modules/@prisma/studio-pcw/build/pcw.js:172:40)
    at async IpcMainImpl.photon (/Applications/Prisma Studio.app/Contents/Resources/app.asar/build/ipc/photon-ipc.js:71:34)

Query:
prisma.eMail.findMany({
  where: {
    AND: [
      {
        id: {
          equals: "d105a13c-6db8-4764-8073-1c88f8a73506",
          mode: "insensitive",
        },
      },
    ]
  },
  take: 100,
  skip: 0,
  select: {
    id: true,
    eMail: true,
    primary: true,
    employee: true,
    eMailVerified: true,
    deleted: true,
    Employee: true,
  }
})
```
Whenever I use the filter I receive this message, even if I use the filter provided by you when opening a relation in a new tab

**Comment by madebysid** [comment] 2021-01-21 10:00
@chrissisura Thanks for reporting this! I unfortunately cannot reproduce this with the schema I'm using, so this *may* be related to your schema. Could you give me relevant parts of your schema? If they're private, you can also DM them to me on [Prisma's Slack](https://slack.prisma.io).

Another thing you could do to help me debug is try running this query outside Studio, in a regular JS scripts, something like this:

```js
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient();

;(async () => {
  const result = await prisma.eMail.findMany({
    where: {
      AND: [
        {
          id: {
            equals: "d105a13c-6db8-4764-8073-1c88f8a73506",
            mode: "insensitive",
          },
        },
      ]
    },
    take: 100,
    skip: 0,
    select: {
      id: true,
      eMail: true,
      primary: true,
      employee: true,
      eMailVerified: true,
      deleted: true,
      Employee: true,
    }
  });

  console.log(result)
})();
```

**Comment by chrissisura** [comment] 2021-01-21 19:42
Ahh great running it in a regular TS script helped me debug the problem! It is caused by `mode: 'insensitive',` as it tries to lower(uuid). 
```
model EMail {
  /// The value of this field is generated by the database as: `gen_random_uuid()`.
  id            String    @id @default(dbgenerated())
  ...
}
```

is there any way to use ``` id    String  @id @default(uuid())``` when using introspection? if yes, do you think this will already fix my problem? Because it seems like lower is being called on database level, which means 
```
CREATE TABLE "EMail" (
    "id" UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY
);
``` 
UUID can't (and maybe shouldn't) be called with lower right? 

Thanks so much for the fast response! I love the new prisma studio app for macOS

**Comment by madebysid** [comment] 2021-02-01 17:20
@chrissisura Sorry for being so late, but I was waiting on 2.16.0 to go out (tomorrow). We have a change with `dbgenerated()` in there. AFAIK, Prisma should no longer touch the value if you use `@default(dbgenerated("gen_random_uuid()")` (but I'm no expert). Could you try updating tomorrow and see if this is still an issue? You'll find the changelog here: https://github.com/prisma/prisma/releases/tag/2.16.0

If you're still seeing this, then your observation looks correct to me, and this most likely is a bug with Prisma Client, in which case, I'll create an issue for you on github.com/prisma/prisma :)
The new argument in `dbgenerated` might unlock a workaround for the time being though!

**Comment by madebysid** [comment] 2021-02-01 17:21
Ah I see there already is one: https://github.com/prisma/prisma/issues/5311

**Comment by madebysid** [comment] 2021-02-10 20:45
So I'm going to go ahead and close this, since Studio cannot really do anything here that Prisma Client does not do. You should follow https://github.com/prisma/prisma/issues/5311 for updates. Once that is resolved, things should automatically start working in Studio too!

**Closed by madebysid** 2021-02-10 20:45 UTC
Labels: bug/1-repro-available, kind/bug
