### ISSUE TITLE
Prisma Studio not working

### ISSUE THREAD

**Issue by Mbentaher** [prisma/studio#963] opened 2022-06-13 14:44 UTC
1. Prisma version (`prisma -v` or `npx prisma -v`):3.15.1

2. Logs from Developer Tools Console or Command line, if any:
Unable to process `count` query
undefined
3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by petradonka** [comment] 2022-06-17 10:59
This looks like a duplicate of https://github.com/prisma/studio/issues/890, so I'm closing this one. Let me know if you think that's not right. In the meantime, you can find more info on the issue above.

**Closed by petradonka** 2022-06-17 10:59 UTC
