### ISSUE TITLE
A `null` Int column value is rendered as `0`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#460] opened 2020-07-06 11:00 UTC
![CleanShot 2020-07-06 at 13 00 17](https://user-images.githubusercontent.com/170299/86586739-ab61eb00-bf88-11ea-83d5-72a2eca1f7e9.gif)

**Comment by madebysid** [comment] 2020-07-06 14:12
@matthewmueller The root cause of this is that `null` is rendered as `0`. The value of the (required) field itself is `null`, which is why it is considered invalid.

**Comment by madebysid** [comment] 2020-07-06 22:34
Fixed on latest `dev`

**Closed by madebysid** 2020-07-06 22:34 UTC
Labels: bug/2-confirmed, kind/bug
