### ISSUE TITLE
Studio Returns One Record When Clicking Reload

### ISSUE THREAD

**Issue by its-kyle-yo** [prisma/studio#393] opened 2020-03-27 04:44 UTC
## Bug description
With multiple records saved (Posts in this case) deleting a post and attempting to refresh the returned records via the `Reload` button on the `Filters` tab Studio will only return one record regardless of the amount present in the database. 

## How to reproduce

1. Open Prisma Studio 
2. Create 2+ records
3. Delete a record and save changes
3. Click Reload 
4. See only one post returned

## Expected behavior

Studio returns all remaining records

## Prisma information 

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id              String       @id @default(cuid())
  externalID      String       @unique
  screen_name     String
  isSubscribed    Boolean      @default(false)
  isNewUser       Boolean      @default(true)
  profileImageUrl String
  name            String
  commitments     Commitment[]
  posts           Post[]
  createdAt       DateTime     @default(now())
}

model Post {
  id                String   @id @default(cuid())
  externalID     String   @unique
  createdAt         String
  deconstructedDate String
  text              String
  source            String
  tags              String[]
  media             Media[]
  author            User
}

model Commitment {
  id           String @id @default(cuid())
  text         String
  type         String
  duration     Int
  durationType String
  author       User
}

model Media {
  id             String  @id @default(cuid())
  post           Post
  externalID String  @unique
  imageUrl       String?
  videoUrl       String?
  type           String
}
```
## Environment & setup

- OS: Mac OS 10.15.3
- Database: PostgreSQL
- Prisma version: prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85
- Node.js version: v13.3.0

**Comment by madebysid** [comment] 2020-03-27 13:25
Hey @its-kyle-yo, welcome! Thanks for reporting this! I'm unable to reproduce the problem though. 

Here's  what I did:

1. Created a `User` (I needed one to connect `posts.author` to), and saved changes
2. Created 4 `Post`s, and saved changes.
3. Deleted 1 `Post`, and saved changes.
4. I see 3 `Posts`.

I might be missing something:

1. I did all creation from within Studio though, did you create things from a script or a different program? It's highly unlikely that that would affect things, but it may be worth a shot.
2. You mentioned `Filters`, so I'm wondering if you have any active? They might be messing with the returned `Post`s. If you do, I'll add the same filters and see if that breaks anything.

Also note that I am on preview025 (it was _just_ released). Maybe give that version a shot as well, this might have been fixed already :D

Let me know what you find!

**Comment by its-kyle-yo** [comment] 2020-03-27 15:29
@madebysid 
Upped the version and I'm still seeing this:
```
╰─ prisma2 -v
@prisma/cli          : 2.0.0-preview025
Current platform     : darwin
Query Engine         : prisma 8814060fa684793b73d07dbfccd4b7777b3361ae (at /Users/kyle/.nvm/versions/node/v13.3.0/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 8814060fa684793b73d07dbfccd4b7777b3361ae (at /Users/kyle/.nvm/versions/node/v13.3.0/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 8814060fa684793b73d07dbfccd4b7777b3361ae (at /Users/kyle/.nvm/versions/node/v13.3.0/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```
I'm currently using prisma2 in an Express REST API with TypeScript and pinging my route that ultimately transforms and saves to the DB in the structure it needs. 

The posts on my end are definitely saving it just seems as if the query given in the console does not change to recognize the change in the number of records. 

As for the filters I don't have any active as I've only used the studio to verify data being saved and associated properly. The filter may or may not be its own separate thing but attempting to change the value of first will remove any given value and default to '1'. 🤔 

![Screen Shot 2020-03-27 at 10 20 08 AM](https://user-images.githubusercontent.com/10294100/77771325-8c140300-7014-11ea-8003-485f965447a9.png)

The reason I point this out is that now in the current version changing the number of records in any direction doesn't update the number of records returned when using `Reload` but does update on a page refresh. 

Is this helpful at all?

**Comment by madebysid** [comment] 2020-03-27 15:46
@its-kyle-yo Ah I get it now, I can reproduce this as well when the records are created from outside Studio. Okay so this is definitely a bug then.
Thanks for the details, I know exactly what's happening here.

The problem is that Studio "counts" records in each table when you first load, and that's the only time it does that. So in this instance, it knows that there is only 1 `Post`.
When you create records from the outside, and try to set the pagination `first` param to `2`, it thinks that that's a typo and "corrects" it back to 1. This is why when you reload the page, the `Post` count is updated, and all records you expect show up again.

We've actually been thinking about cleaning this interaction up a bit, because it is currently verbose and is pretty hard to handle (in code, and in the UI). There's more details here if you're interested: https://github.com/prisma/studio/issues/309

@matthewmueller I think this use case of creating/deleting/updating records from the outside needs a little bit of reasoning on our end, let's discuss this in our next meeting!

**Comment by madebysid** [comment] 2020-03-27 15:47
Most of that last comment might be me rambling, so you can ignore most of it @its-kyle-yo :D

**Comment by its-kyle-yo** [comment] 2020-03-27 15:49
Haha no worries! Happy to help and happy I was able to explain it in only 3 comments 🤣

**Comment by madebysid** [comment] 2020-03-31 15:17
@its-kyle-yo Could you try out alpha.1012? It includes a fix for this. You should now be able to create records outside Studio and have them show up by clicking `Reload`. The `first` field should also no longer try to correct itself. (That was weird to begin with, I must admit)

Let me know if you still run into issues / notice any other UX issues!

**Comment by its-kyle-yo** [comment] 2020-03-31 22:27
@madebysid After getting things upgraded it still looks like creating a post via a Postman/Insomnia etc. reloading still doesnt update the count when pressing `Reload`. As well the `first` field does seem to show the same issue as before.

**Comment by madebysid** [comment] 2020-04-01 08:36
@its-kyle-yo Huh. In your DevTools Console, there should be a log with Studio's version. Could you check to make sure it is 0.219.0 or above? The old behaviour makes me think you aren't on the right version. I might be wrong though.

Oh also, are you on the beta.1 version? That unfortunately went out before this fix was released, so you'll have to stick to the alpha.

**Comment by its-kyle-yo** [comment] 2020-04-07 02:05
I am on `beta.1`. I can change to alpha releases and check.

**Comment by its-kyle-yo** [comment] 2020-04-07 02:11
@madebysid it looks as if I'm on `0.216.0`. Is there an easy way to swap to the recommended version?

**Comment by madebysid** [comment] 2020-04-23 13:51
Going to close this, since I haven't been able to see it again, but if you do, please let me know and I'll reopen!

**Closed by madebysid** 2020-04-23 13:51 UTC
Labels: bug/2-confirmed, kind/bug
