### ISSUE TITLE
Changing optional relation into required relation causes crash

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#274] opened 2019-10-29 05:30 UTC
Changing this:
```graphql
model Venue {
  VenueRegion   VenueRegion? @relation(name: "OVenuesToRVenueRegion")
  name
}
model VenueRegion {
  Venues        Venue[]      @relation(name: "OVenuesToRVenueRegion")
  name
}
```

to this:
```graphql
model Venue {
  VenueRegion   VenueRegion @relation(name: "OVenuesToRVenueRegion")
  name
}
model VenueRegion {
  Venues        Venue[]      @relation(name: "OVenuesToRVenueRegion")
  name
}
```
causes an error. In this case, each model has a single record saved in the SQLite database, with the single `VenueRegion` record (e.g. `name`: “San Francisco Bay Area”) already connected to the `Venue` single record (e.g. `name`: “Dolores Park”).
```
Reason: Application logic invariant error: received null value for field VenueRegion which may not be null in query-engine/core/src/response_ir/read.rs:223:26
```

**Comment by heymartinadams** [comment] 2019-11-13 05:54
Awesome. Shall I close this comment?

**Comment by madebysid** [comment] 2020-02-07 13:59
@heymartinadams `prisma2 dev` doesn't exist anymore, but I did find the root cause for this, and it is now fixed and out on alpha (`npm i prisma2@alpha`). Could you try it out and let me know if you're still seeing this?

**Closed by madebysid** 2020-02-07 13:59 UTC
Labels: process/needs-design

**Comment by heymartinadams** [comment] 2020-02-07 17:24
Not seeing this anymore. Thanks, Siddhant.
