### ISSUE TITLE
Cannot read property 'response' of null when prisma studio launches

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [prisma/studio#485] opened 2020-08-09 14:46 UTC
1. Prisma2 version (`prisma -v`):
2.4.1

2. Logs from Developer Tools Console, if any:
```
![image](https://user-images.githubusercontent.com/33642056/89734997-fc03b280-da24-11ea-863f-3f3bc09a77ac.png)

```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Yes
4. Prisma2 schema (if relevant):
```
model User {
  id    String  @unique
  email String  @unique
}
```

**Comment by madebysid** [comment] 2020-08-10 09:27
Hey @nerdthatnoonelikes, thanks for reporting! Since this is such a basic use case, I'm guessing something somewhere else is messed up. Although Studio on the latest `dev` version already does this (thanks to https://github.com/prisma/studio/issues/483), could you also try clearing out your `~/.cache` directory (on macOS or Linux) or your `%appdata%/Prisma Studio` directory on Windows?

Do you also see any logs on your terminal itself?

Finally, I released 2.5.0-dev.11 only on Friday, so just to be 100% sure you didn't run into this before it, could you confirm that the version of `@prisma/cli` is `2.5.0-dev.11` or higher? Thanks!

**Comment by Smartmikey** [comment] 2020-08-24 16:53
I am currently having the error too

**Comment by Smartmikey** [comment] 2020-08-24 16:55
I'm running on v 2.5.1

**Comment by madebysid** [comment] 2020-08-24 17:06
@Smartmikey Did you also try clearing out the cache folders? Do you see any logs in the terminal and/or in our browser's DevTools?

**Comment by Smartmikey** [comment] 2020-08-24 17:12
Terminal
at async WebSocket.StudioServer.onWSMessage (C:\.....\node_modules\@prisma\cli\build\index.js:2:459735) { query: 'Promise.all([\n    prisma.user.count(),\n])' }

Browser error
studioBundle.js:395 [BootstrapStore.init] Studio bootstrap failed Objectmessage: "Cannot read property 'response' of null"stack: "TypeError: Cannot read property 'response' of null↵    at Xo.init (http://localhost:5555/studioBundle.js:395:154854)"__proto__: Object Object

Uncaught (in promise) Error: Studio bootstrap failed
    at Bt (studioBundle.js:395)
    at Xo.init (studioBundle.js:395)



I have cleared cache and the error still persist

**Comment by Smartmikey** [comment] 2020-08-31 07:08
Hey, I found the fix.

it was an error from myself 

i didn't run :- `npx prisma migrate up --experimental ` after creating the first model. but after running that now, the studio is working perfectly

thanks for your help and concern 👍

**Comment by madebysid** [comment] 2020-08-31 08:37
Ah great, it's a little weird that the error is so cryptic. I'll try and reproduce this and see if it can be improved. I'll close this issue for now then.

**Closed** 2020-08-31 08:37 UTC
Labels: bug/0-needs-info, kind/bug
