### ISSUE TITLE
Rethink "New tab flow"

### ISSUE THREAD

**Issue by schickling** [prisma/studio#129] opened 2019-09-12 13:56 UTC
![image](https://user-images.githubusercontent.com/1567498/64790090-ce448e00-d575-11e9-91c8-22a77bc6b929.png)
![Image 3](https://user-images.githubusercontent.com/1567498/64790110-d997b980-d575-11e9-8a28-6f8781b6534b.jpeg)

**Comment by idan** [comment] 2019-10-01 18:00
@schickling @kuldar What was the goal here? What will this improve/accomplish?

**Comment by idan** [comment] 2019-10-02 16:43
Seems like a duplicate of #53?

**Comment by madebysid** [comment] 2020-08-19 15:38
@hrescak has simplified this now, so there is only way to navigate. Closing!

**Closed by madebysid** 2020-08-19 15:38 UTC
Labels: kind/discussion, kind/feature, team/design, topic: design
