### ISSUE TITLE
Model named "@@id"

### ISSUE THREAD

**Issue by SMasiu** [prisma/studio#806] opened 2021-11-27 19:11 UTC
**Describe the bug**
Seems that Prisma studio doesn't pick up the name given in the model

**To Reproduce**
1. Create prisma model
```prisma
model GroupMember {
  role Int
  groupId Int
  group    Group  @relation(fields: [groupId], references: [id])
  userId Int
  user   User @relation(fields: [userId], references: [id])
  
 @@id([groupId, userId], name: "primaryKey")
}
```
2. Open Prisma studio
3. Update role

**Error message**
Invalid `prisma.groupMember.update()` invocation:

```javascript
{
  where: {
    groupId_userId: {
    ~~~~~~~~~~~~~~~~
      groupId: 1,
      userId: 3
    }
  },
  data: {
    role: 1
  }
}
```

**Comment by madebysid** [comment] 2021-12-27 16:48
Hey @SMasiu, apologies on the late response here, but we've been able to reproduce this. I'll let you know when a fix is out!

**Comment by madebysid** [comment] 2022-01-06 12:25
This should be fixed on the latest Prisma CLI `dev` version (`3.8.0-dev.46` as of writing). Could you update your CLI and let me know if you're still seeing this?
This will make it the stable CLI with the next release (next Tuesday). You can keep using the `dev` version if you'd like, but I'd recommend upgrading to `3.8.0` when it goes out, since `dev` versions are mostly for internal use and may contain unannounced breaking changes.

Let me know if you're still seeing this!

**Closed by madebysid** 2022-01-06 12:25 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by SMasiu** [comment] 2022-01-06 15:41
I've upgraded Prisma to `3.8.0-dev.46` version and I'm not getting this error anymore.

Thanks, guys for fixing that bug.
