### ISSUE TITLE
PlanetScale Connect to one/many to many relations 1105 error

### ISSUE THREAD

**Issue by bardiaheshmati** [prisma/studio#814] opened 2021-12-18 14:52 UTC
I'm testing my existing schema on PlanetScale and i'm getting an error when i'm trying to connect relations

```js
Message: 
Invalid `prisma.product.update()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol tino.Product.id not found", state: "HY000" })) })

Query: 
prisma.product.update(
{
  where: {
    id: "69d7ee03-6d9e-46ec-a2ae-0b40e58158e1",
  },
  data: {
    category: {
      connect: {
        id: "0226b8aa-4fc5-4b20-801b-6a62b0ca8711",
      },
    },
  },
  select: {
    id: true,
    category: true,
    categoryId: true,
  },
}
)
```

Schema
```js
  model Category {
    id          String       @id @default(uuid()) @db.Char(36)
    name        String       @db.VarChar(255)
    description String?
    createdAt   DateTime     @default(now())
    updatedAt   DateTime     @updatedAt
    active      Boolean      @default(true)
    products    Product[]
  
    @@unique([id, active])
  }
  
  model Product {
  id           String         @id @default(uuid()) @db.Char(36)
  sku          String?        @db.VarChar(255)
  name         String         @db.VarChar(255)
  categoryId   String?
  category     Category?      @relation(fields: [categoryId], references: [id], onDelete: SetNull)
}
```

I have no issues when testing locally so i assume it has to do something with planetScale.

**Comment by janpio** [comment] 2021-12-18 19:39
Duplicate of https://github.com/prisma/prisma/issues/10758 I assume

**Closed by janpio** 2021-12-18 19:39 UTC
