### ISSUE TITLE
Relation accordion does not indicate which items are/is connected

### ISSUE THREAD

**Issue by janpio** [prisma/studio#436] opened 2020-07-02 09:58 UTC
This is from current version of prisma.studio/preview?project=chinook

![image](https://user-images.githubusercontent.com/183673/86344941-34141a80-bc5b-11ea-91bd-310eb6ca021d.png)

Before opening the relation view the table indicated there were 10 connected items (see https://github.com/prisma/studio/issues/435). I can not see which 10 those are when opening it.

**Comment by janpio** [comment] 2020-07-02 10:03
Similar problem for to-1 relation:
![image](https://user-images.githubusercontent.com/183673/86345611-09769180-bc5c-11ea-954c-9e86ae72ccff.png)

**Comment by madebysid** [comment] 2020-07-02 13:20
Is this the same as https://github.com/prisma/studio/issues/435?
If so, then I'm aware of this, fixing this requires a but of refactoring in some parts, which I'm doing right now!

**Comment by madebysid** [comment] 2020-07-02 13:21
Ah the two are different

**Comment by madebysid** [comment] 2020-07-03 16:22
This will be fixed with the next `dev` version of @prisma/cli (currently building)

**Comment by madebysid** [comment] 2020-07-03 17:37
This is a little flaky still

**Comment by janpio** [comment] 2020-07-03 17:39
Yep, only a few of the items are selected: 
![image](https://user-images.githubusercontent.com/183673/86489510-d7048b80-bd64-11ea-80a6-321d79beac07.png)

**Comment by janpio** [comment] 2020-07-03 17:39
Oh, and when closing the accordion only 100 are selected any more.

**Comment by madebysid** [comment] 2020-07-06 22:30
I think this should be okay now.

**Comment by janpio** [comment] 2020-07-07 10:06
Still broken on prisma.studio:
![image](https://user-images.githubusercontent.com/183673/86766082-54244f00-c04a-11ea-854d-798e1a047893.png)

**Comment by madebysid** [comment] 2020-07-20 14:25
@janpio Back then prisma.studio was broken (not up to date), but it is now. Could you check and close if fixed?

**Comment by janpio** [comment] 2020-07-20 15:42
Still broken on PlaylistId 1 when I scroll around:
![image](https://user-images.githubusercontent.com/183673/87957341-6a9dc200-cab0-11ea-99fa-a343c6985a9a.png)

**Comment by madebysid** [comment] 2020-08-19 15:29
@janpio Could you re-check on prisma.studio / CLI and close if this is still an issue? This is pretty old now and I haven't been able to reproduce lately either.

**Comment by janpio** [comment] 2020-08-19 18:17
![image](https://user-images.githubusercontent.com/183673/90674037-db273280-e258-11ea-87f2-e776692f65f7.png)

1. https://prisma.studio/preview?project=chinook
2. Open "Playlist" in tab
3. Click on PlayliStrack relations of PlaylistId 1
4. See some checkboxes for `1`
5. Scroll to bottom and wait for it to load - see some higher PlaylistId number and no check boxes
6. Scroll back up until you are at 1 again (further down though) and see what I pasted above

**Comment by madebysid** [comment] 2020-08-24 13:56
I guess I'll close this. Perhaps create a new issue for the "problem" you're seeing?

Not even sure if that's something that'll come up in the real world, since you'll likely know _something_ about the record you're trying to connect, and hence can search.

**Closed by madebysid** 2020-08-24 13:56 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by janpio** [comment] 2020-08-24 18:47
So the change in behavior is intended?

**Comment by madebysid** [comment] 2020-08-28 18:42
Okay sorry about the delay in my response, but I was finishing this up.
There's now a new `Skip to unconnected records` button in this table that will make what you're doing much easier. You can also scroll of course (as before).

CLI build is failing, but it is available on https://prisma.studio
