### ISSUE TITLE
Feature request: Being able to select entries to download/export as JSON

### ISSUE THREAD

**Issue by jayanth1991** [prisma/studio#634] opened 2021-02-19 15:34 UTC
Hi,

Firstly, just want to say that this is an amazing tool.

It would be great to be able to select specific entries in a db table via the studio:
![image](https://user-images.githubusercontent.com/1319597/108525306-ef96c700-729d-11eb-8578-86bc9cdc2cf0.png)
And download/export them as a JSON object. Not sure if this is already an option, but would be really interested to see it if it doesn't already exist.

**Comment by madebysid** [comment] 2021-02-20 11:49
Hey Jayanth! Thanks for the feature request! This sounds like a cool thing to add. 
IIRC this used to be a thing, but I must have removed it accidentally or something.

**Comment by madebysid** [comment] 2021-02-26 21:04
Hey @JMavs @omar-dulaimi I was able to reproduce this as well and I've now fixed this in Prisma CLI `2.18.0-dev.48`. If this is blocking, you should be able to `npm install prisma@dev` to get this immediately. However, I'd recommend updating to the next stable version when it comes out, since `dev` versions are mostly for internal use and may contain unannounced breaking changes.

This will also make it to stable v2.18.0 scheduled for this Tuesday!

**Closed by madebysid** 2021-02-26 21:04 UTC
Labels: kind/feature

**Comment by jayanth1991** [comment] 2021-02-26 21:06
Thanks for the quick turnaround! 🔥

**Comment by madebysid** [comment] 2021-02-26 21:11
Oh, to clarify, the way I've done this is if you select a few rows and press Cmd/Ctrl+C, a JSON object representing your records should be copied to your clipboard.
Clipboard copies can sometimes be finnicky, so Cmd/Ctrl+C should also log this JSON object to your browser's DevTools console!
