### ISSUE TITLE
After editing relation only the number of unsaved changes is shown in main table

### ISSUE THREAD

**Issue by janpio** [prisma/studio#439] opened 2020-07-02 10:02 UTC
This is from current version of prisma.studio/preview?project=chinook

After https://github.com/prisma/studio/issues/437 I see this in the main table:
![image](https://user-images.githubusercontent.com/183673/86345412-cae0d700-bc5b-11ea-8fc9-71cd4e0c2018.png)
No more mention of the 10 actually connected items.

**Comment by madebysid** [comment] 2020-07-02 13:23
While this looks like a different issue, the root cause of this is the same as https://github.com/prisma/studio/issues/436. Happens because the already connected records are not "selected" when you open the accordion. Closing this one in favor of #436!

**Comment by janpio** [comment] 2020-07-02 15:45
Let's keep this open so this can be checked visually when closed.

**Comment by madebysid** [comment] 2020-07-03 16:24
This will be fixed with the next `dev` version of @prisma/cli (currently building)

**Closed by madebysid** 2020-07-03 16:24 UTC
Labels: bug/2-confirmed, kind/bug
