### ISSUE TITLE
This is the default Graphql-API example (javascript version) error

### ISSUE THREAD

**Issue by alaarihan** [prisma/studio#312] opened 2019-12-12 20:47 UTC
<Anything that helps us reproduce the error goes here>

**Error dump**
Error in Photon: 
Error: undefined target="exit" timestamp="2019-12-12T20:44:50.705Z" fields={"message":"1"}
    at NodeEngine.engineReady (/home/alaa/.cache/prisma/studio/home-alaa-NodeProjects-tmp-prisma2Example/runtime/index.js:3533:23)
    at async /home/alaa/.cache/prisma/studio/home-alaa-NodeProjects-tmp-prisma2Example/runtime/index.js:3456:21

**Stacktrace**
Error: Error in Photon: 
Error: undefined target="exit" timestamp="2019-12-12T20:44:50.705Z" fields={"message":"1"}
    at NodeEngine.engineReady (/home/alaa/.cache/prisma/studio/home-alaa-NodeProjects-tmp-prisma2Example/runtime/index.js:3533:23)
    at async /home/alaa/.cache/prisma/studio/home-alaa-NodeProjects-tmp-prisma2Example/runtime/index.js:3456:21
    at PhotonFetcher.<anonymous> (/home/alaa/.cache/prisma/studio/home-alaa-NodeProjects-tmp-prisma2Example/index.js:72:31)
    at Generator.throw (<anonymous>)
    at rejected (/home/alaa/.cache/prisma/studio/home-alaa-NodeProjects-tmp-prisma2Example/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by madebysid** [comment] 2019-12-18 12:42
Hey @alaarihan, are you able to reliably reproduce this on `latest` (preview018.1)? This usually happens when the prisma2 binary failed to download correctly.

Does this also only happen with Studio? Are you able to manually run a script with some photon requests in it?

**Comment by alaarihan** [comment] 2019-12-19 03:23
@madebysid I just tried again with the latest preview release, I had the same error when I run studio, I noticed one thing, I'm running manjaro linux and the downloaded binary was debian! is this the reason behind the error?

**Comment by madebysid** [comment] 2019-12-19 09:43
@alaarihan That should be okay, we do not have a dedicated build for Arch yet, so the debian build maps to it (details here: https://github.com/prisma/specs/tree/master/binaries#linux-distributions-and-versions). That *should* work.
Did you try manually running a script with some photon requests?

Perhaps something like:
```js
const { Photon } = require('@prisma/photon');
const photon = new Photon();

(() => {
  console.log(await photon.users.findMany());
})()
```

I just want to make sure that this is specific to Studio :)

**Comment by alaarihan** [comment] 2019-12-19 10:13
I've got this error when I ran your script:
```
Invalid `photon.()` invocation in /home/alaa/NodeProjects/tmp/prisma2Example3/src/index.js:11:34



undefined target="exit" timestamp="2019-12-19T10:07:53.269Z" fields={"message":"1"}
    at PhotonFetcher.<anonymous> (/home/alaa/NodeProjects/tmp/prisma2Example3/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/alaa/NodeProjects/tmp/prisma2Example3/node_modules/@prisma/photon/index.js:6:65)
(node:6164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by alaarihan** [comment] 2019-12-19 10:16
Sorry this is my mistake, I will run the script and post the result now

**Comment by alaarihan** [comment] 2019-12-19 10:21
I installed the default js script example and this is the result when I run it:
```
> script@1.0.0 dev /home/alaa/NodeProjects/tmp/prisma2Example5
> node ./script.js

Error: 
Invalid `const user1 = await photon.users.create()` invocation in /home/alaa/NodeProjects/tmp/prisma2Example5/script.js:7:36

   3 
   4 // A `main` function so that we can use async/await
   5 async function main() {
   6   // Seed the database with users and posts
→  7   const user1 = await photon.users.create(

undefined target="exit" timestamp="2019-12-19T10:19:45.431Z" fields={"message":"1"}
    at PhotonFetcher.<anonymous> (/home/alaa/NodeProjects/tmp/prisma2Example5/node_modules/@prisma/photon/index.js:65:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/alaa/NodeProjects/tmp/prisma2Example5/node_modules/@prisma/photon/index.js:6:65)
(node:6905) UnhandledPromiseRejectionWarning: Error: undefined target="exit" timestamp="2019-12-19T10:19:45.431Z" fields={"message":"1"}
    at NodeEngine.engineReady (/home/alaa/NodeProjects/tmp/prisma2Example5/node_modules/@prisma/photon/runtime/index.js:3533:23)
    at async /home/alaa/NodeProjects/tmp/prisma2Example5/node_modules/@prisma/photon/runtime/index.js:3456:21
(node:6905) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6905) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by madebysid** [comment] 2019-12-19 11:25
Ah so it does not seem specific to Studio. Since you're also able to reproduce on a new project, my initial guess about a corrupted download is probably wrong. I'm guessing this means you're unable to use prisma2 at all right now?
We're tracking this error here:  https://github.com/prisma/photonjs/issues/357

It seems this is a blanket error for a bunch of stuff. I'd recommend following that issue for updates as well. As soon as we figure out what the root cause is, I'll let you know here as well!

**Comment by alaarihan** [comment] 2019-12-19 17:10
No I don't think it's specific to Studio but I used the link from Studio to report it so I found my self posting here, I can't use prisma2 at all because of this error, thank you @madebysid for updating me and I hope it will be fixed soon :)

**Comment by matthewmueller** [comment] 2020-03-03 11:58
@alaarihan are you still running into this? Since the referenced issue is closed, I'll close this issue. Happy to re-open though if you're still having issues!

**Closed by matthewmueller** 2020-03-03 11:58 UTC
Labels: bug/1-repro-available, kind/bug
