### ISSUE TITLE
Navigating from relations table triggered `Error: Could not find appropriate InputType for this field type. This should never happen.`

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/studio#554] opened 2020-09-28 17:49 UTC
I tried navigating to a view from the relations table and got a crash.

Here's my schema.prisma:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("PG_DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
}

model Customer {
  id       Int     @id @map("CustomerId")
  name     String  @map("Name")
  location String  @map("Location")
  email    String  @map("Email")
  orders   Order[]
}

model Order {
  id         Int      @id @default(autoincrement()) @map("Id")
  createdAt  DateTime @map("CreatedAt")
  total      Int      @map("Sum")
  customerId Int      @map("CustomerId")
  customer   Customer @relation(fields: [customerId], references: [id])
}
```

The script I used to populate some test values:
```ts
  import { PrismaClient } from '@prisma/client'
  const prisma = new PrismaClient()
  await prisma.order.deleteMany({})
  await prisma.customer.deleteMany({})

  const herve = await prisma.customer.create({
    data: {
      id: 1,
      email: 'labas@prisma.io',
      location: 'Berlin, Germany',
      name: 'Herve Labas',
      orders: {
        create: {
          total: 69,
          createdAt: new Date()
        }
      }
    },
    include: {
      orders: {}
    }
  })
  const test = await prisma.customer.create({
    data: {
      id: 2,
      email: 'test@test.com',
      location: 'Undisclosed',
      name: 'Test hispster e-mail',
    }
  })
```

I was on the Customer table, opened the `Order` relation, navigated to the tab using `Show in new tab`.
Once there, a filter was initialized and the error got triggered once trying to open the filter.

1. Prisma version (`prisma -v` or `npx prisma -v`):

`2.8.0-dev.55`

2. Logs from Developer Tools Console or Command line, if any:
```
"prisma.order.findMany({
  where: {
    AND: [
      {
        customer: { NOT: {"id":1} },
      },
    ]
  },
  take: 100,
  skip: 0,
  select: {
    id: true,
    createdAt: true,
    total: true,
    customerId: true,
    customer: true,
  }
})"
```
Then first error:
```
TypeError: this.props.resizeRowForRelation is not a function
    at handleClickRelation (studioBundle.js:395)

```
![image](https://user-images.githubusercontent.com/431257/94467293-04759f80-01c3-11eb-83c1-a108f7129f10.png)

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes

**Comment by madebysid** [comment] 2020-10-05 11:58
I figured out what the problem is: Opening this relation in a new tab adds a filter to a relation field (something like: `where: { order: { id: 1 } }`. The filter itself is correct, so you see the right rows, but the UI doesn't know how to render a filter on a relation field (you cannot add a where filter to a relation field from the UI at all), so it crashes.

I cannot skip over filters on relation fields, because then you'd see "no filters" even when the count clearly says `1`.

For now, I'll render a regular row in the Filters UI, with the value of the text box set to `{ order: { id: 1 } }` to fix this.

However, there are a couple of other related issues:
1. There would still be no way to add a filter on a relation field from the UI (except if you add it using the `Open in new tab`, as this issue does)
2. Editing of this filter would technically be possible, but not recommended (AKA painful) since there's no help (no autocomplete, no validity checks etc.)

Do we want to support filters on relation fields @hrescak? If so, we can pick https://github.com/prisma/studio/issues/520 up

**Comment by thebiglabasky** [comment] 2020-10-05 13:56
Supporting that as a 2-step process could be good indeed:
* Initial: don't crash and show a filter that is not even editable could work. Alternatively, having it editable without any editing help, typos in there basically making the filter invalid as for other fields
* Later: having better support for filtering on relations (need to define "better" though) Probably something with some kind of sub-menu could be good, although I'd leave that to @hrescak to coordinate if/once we get there.

I'm not sure that we should prioritize the "Later" milestone just yet until we've heard more about it.

**Comment by madebysid** [comment] 2020-10-05 15:46
Let me close this then, since I've done what is suggested in `Initial` with CLI `2.9.0-dev.43`. Let's continue the conversation on #520

**Closed by madebysid** 2020-10-05 15:46 UTC
Labels: bug/2-confirmed, kind/bug
