### ISSUE TITLE
Bug: Found argument '--enable-experimental' which wasn't expected. Did you mean --enable-playground?

### ISSUE THREAD

**Issue by nickreynke** [prisma/studio#483] opened 2020-08-05 05:29 UTC
1. Prisma2 version (`prisma -v`):

```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.4.0
Current platform     : darwin
Query Engine         : query-engine 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules/@prisma/cli/prisma-fmt-darwin)
```

2. Logs from Developer Tools Console, if any:

After running `npx prisma studio --experimental`:

```
Environment variables loaded from prisma/.env
Generating Prisma Client ... done
Studio started at http://localhost:5555
Error in request:  PrismaClientInitializationError: Query engine exited with code 1

error: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context
        Did you mean --enable-playground?
USAGE:
    query-engine-darwin --enable-playground
For more information try --help
    at PrismaClientFetcher.request (/Users/xxx/.cache/prisma/studio/xxx/runtime/index.js:1:211294)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  query: 'Promise.all([\n' +
    '    prisma.user.count(),\n'
    // And every other count ...
    '])'
}
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes, for version `^2.4.0-dev.60`. Even after clearing the cache.

**Comment by madebysid** [comment] 2020-08-06 04:24
Hey @nickreynke,  thanks for reporting. Super weird that so many of you are seeing it but I don't. Let me dig deeper and I'll get back to you people asap

**Comment by janpio** [comment] 2020-08-06 07:44
I noticed you are running the global command `prisma -v` to get the version, but using the local `npx prisma studio` to run Studio. Can you please also share your `npx prisma -v` output?

Thanks.

**Comment by tommypater** [comment] 2020-08-06 11:53
Hello, yes same error for me,

Here my "npx prisma -v" output
```
Environment variables loaded from prisma\.env
@prisma/cli          : 2.4.0
Current platform     : windows
Query Engine         : query-engine 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\prisma-fmt-windows.exe)
```

I use nexus-plugin-prisma@0.17.0 who use "@prisma/client": "^2.4.0"

My "npm list --depth=0"
```
+-- @apollo/client@3.1.2
+-- @types/bcryptjs@2.4.2
+-- @types/cors@2.8.7
+-- @types/jsonwebtoken@8.5.0
+-- @types/multer@1.4.3
+-- @types/multer-s3@2.7.7
+-- @types/next@9.0.0
+-- @types/node@14.0.27
+-- @types/pify@3.0.2
+-- @types/react@16.9.44
+-- @types/react-dom@16.9.8
+-- @types/react-select@3.0.16
+-- @types/sharp@0.25.1
+-- @types/styled-jsx@2.2.8
+-- @types/ws@7.2.6
+-- @typescript-eslint/eslint-plugin@3.8.0
+-- @typescript-eslint/parser@3.8.0
+-- apollo-cache-inmemory@1.6.6
+-- apollo-client@2.6.10
+-- apollo-link@1.2.14
+-- apollo-link-context@1.0.20
+-- apollo-link-error@1.1.13
+-- apollo-link-http@1.5.17
+-- aws-sdk@2.726.0
+-- bcryptjs@2.4.3
+-- cors@2.8.5
+-- cross-env@7.0.2
+-- dotenv@8.2.0
+-- eslint@7.6.0
+-- eslint-config-prettier@6.11.0
+-- eslint-plugin-prettier@3.1.4
+-- eslint-plugin-react@7.20.5
+-- express@4.17.1
+-- framer-motion@2.3.0
+-- UNMET PEER DEPENDENCY graphql-middleware@^2.0.0 || ^3.0.0 || ^4.0.0
+-- graphql-request@2.0.0
+-- graphql-shield@7.3.3
+-- isomorphic-unfetch@3.0.0
+-- jsonwebtoken@8.5.1
+-- moment@2.27.0
+-- multer@1.4.2
+-- multer-s3@2.9.0
+-- next@9.5.1
+-- next-pwa@3.1.1
+-- nexus@0.26.1
+-- nexus-plugin-prisma@0.17.0
+-- node-fetch@2.6.0
+-- node-mailjet@3.3.1
+-- pify@5.0.0
+-- places.js@1.19.0
+-- postcss-flexbugs-fixes@4.2.1
+-- postcss-nested@4.2.3
+-- postcss-preset-env@6.7.0
+-- prettier@2.0.5
+-- react@16.13.1
+-- react-date-picker@8.0.1
+-- react-day-picker@7.4.8
+-- react-dom@16.13.1
+-- react-google-login@5.1.21
+-- react-range@1.6.7
+-- react-select@3.1.0
+-- sharp@0.25.4
+-- slugify@1.4.5
+-- ts-node@8.10.2
+-- ts-node-dev@1.0.0-pre.56
`-- typescript@3.9.7
```

Thanks for your works =)

**Comment by madebysid** [comment] 2020-08-07 08:38
Hello everyone, if anyone's running into this when running a global install of the `prisma` CLI on a project, could you make sure the global AND the local version of `@prisma/cli` & `@prisma/client` are updated to the latest version?
I still believe this is a bug, but doing so might help you avoid this issue till I fix it.

If anyone's interested, here's what I believe is happening: Studio uses Prisma Client internally, which, in turn, uses a binary we call the Query Engine. All three of these entities have versions that are usually kept in sync. I believe the issue is that a newer version of Studio (installed globally) is trying to invoke an older version of the Query Engine (installed locally), which is why you're seeing this. Again, this shouldn't be happening. A global install of the CLI should always use a global install of Studio, Client & the Query Engine, and the same should hold for local installs. I will look into why this is happening.

**Comment by tommypater** [comment] 2020-08-07 08:53
For my part, I do not use / not installed prisma globally (only locally).

Would you like me to try using Studio with prisma installed globally to test?

**Comment by madebysid** [comment] 2020-08-07 09:58
@tommypater Ah you're using Nexus, so you likely don't even have the CLI or Client directly installed right? Do you have a repo I can clone to actually see it happen?

**Comment by tommypater** [comment] 2020-08-07 14:07
@madebysid Yes ! And I have no public repo, i can create one, but it may not be useful, at least concerning me.

I solved the problem in a strange way that I don't fully understand : By renaming the project root folder.

Where can this type of "cache" by path come from? Is it related to windows? I seem to remember having this type of problem with VS Code and autocompletion GraphQL, I had to rename the project root folder as well.

If I rename the root folder, with the old name, the error comes back.

-- Very sorry for my approximate english

**Comment by madebysid** [comment] 2020-08-07 14:28
@tommypater Okay so since Studio uses Prisma Client internally, it will generate Client in a temporary location that is derived from your project name. On windows, you should be able to find a folder called `Prisma Studio` in your `AppData` folder. By renaming your project, you've essentially "opened" a new project with Studio.

So my theory then is that there's an old version of the Query Engine binary in this faulty project of yours. There's a way to check: If you open up this "faulty" project name's folder in your `AppData\Prisma Studio` folder, and run the query engine binary in there in a Terminal window with a `-v` flag, is the printed version different from what `npx prisma studio -v` shows you? Could you also post this version here?

(I know, this is beginning to get a little too vague for everyone else on this thread who don't have access to Studio's code, so I do apologize :( )

Anyway, I've just added a line of code to Studio that will clear this directory before generating Client, which should (hopefully) avoid issues like this in the future. It'll be like opening a new project with Studio every time.

**Comment by tommypater** [comment] 2020-08-07 15:33
-- in the \AppData\Roaming\Prisma\Studio\[OLD-FOLDER-NAME]

$ ./query-engine-windows.exe -V
`query-engine 6c777331554df4c3e0a90dd841339c7b0619d0e1`

And ! In the runtime folder, an other query-engine-windows.exe.
(I guess it shouldn't be there since in the new folder created with new name folder, there is no query-engine-windows.exe in runtime folder)

And in folder /runtime (of the same folder AppData) :
$ ./runtime/query-engine-windows.exe -V
`query-engine 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6` (old version, right ?)

And "npx prisma studio -v" (i don't know if the "studio" word is an extra but:)
`Unknown or unexpected option: -v`

"npx prisma -v"
```Environment variables loaded from prisma\.env
@prisma/cli          : 2.4.0
Current platform     : windows
Query Engine         : query-engine 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 6c777331554df4c3e0a90dd841339c7b0619d0e1 (at node_modules\@prisma\cli\prisma-fmt-windows.exe)```

Good for the clearing folder =)

**Comment by TheBeachMaster** [comment] 2020-08-07 15:47
Ran into this  issue too.

My setup does not allow a global installation.

Nuking the `node_modules` folder does not help much either.

```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.4.1
Current platform     : darwin
Query Engine         : query-engine 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/prisma-fmt-darwin)
```

**Comment by madebysid** [comment] 2020-08-07 16:44
Oh my, `2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6` is actually from April of this year. We definitely did not have the `--enable-experimental` flag back then, and the query-engine binary used to reside in the runtime directory, which is why you're seeing two of them. I think somehow this old version of the binary was being used, even though a newer one exists. Very intriguing.

I've just released a new version of Studio, and it clears the cache directory before attempting to generate Client (as I mentioned above), and so I'd like you to try it out on your fauly project, to see if that fixes your issue. Since Nexus doesn't have a direct dependency on the CLI / Client, the easiest / fastest way for you to get the new Studio would be to run `npm i @prisma/cli@2.5.0-dev.11 @prisma/client@2.5.0-dev.11` in your project. What this will do is add these two packages to your package.json, and so, when you run `npx prisma studio` this time, you should load up the latest version (rather than the one that ships with `nexus-prisma`). You can verify by going to your browser's tab where Studio opens, opening up your DevTools console, and there should be a log on the very top, saying `Studio version: 0.246.0`. If so, let me know if you still see the error in the OP.

This is all temporary of course, you shouldn't need to have `@prisma/cli` & `@prisma/client` in your `package.json`, but till the Nexus team releases the next version of `nexus-prisma`, this is the fastest way for you to "override" the CLI and Client versions.

**Comment by madebysid** [comment] 2020-08-07 16:50
Oh my, 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6 is actually from April of this year. We definitely did not have the --enable-experimental flag back then, and the query-engine binary used to reside in the runtime directory, which is why you're seeing two of them. I think somehow this old version of the binary was being used, even though a newer one exists. Very intriguing.

I've just released a new version of Studio, and it clears the cache directory before attempting to generate Client (as I mentioned above), and so I'd like you to try it out on your fauly project, to see if that fixes your issue. Since Nexus doesn't have a direct dependency on the CLI / Client, the easiest / fastest way for you to get the new Studio would be to use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/). Specifically, add this to your package.json and run `yarn`:
```
"resolutions": {
   "@prisma/cli": "2.5.0-dev.11",
   "@prisma/client": "2.5.0-dev.11",
   "@prisma/sdk": "2.5.0-dev.11"
}
```
When you now run `npx prisma studio`, you should load up the latest version (rather than the one that ships with nexus-prisma). You can verify by going to your browser's tab where Studio opens, opening up your DevTools console, and there should be a log on the very top, saying Studio version: 0.246.0. If so, let me know if you still see the error in the OP.

This is all temporary of course, once 2.5.0 actually goes out, the Nexus team will release a new version of the `nexus-prisma` plugin and you'll be able to get rid of the `resolutions` key from your `package.json`.

To everyone else seeing this issue, please try doing the same. If you're not using Nexus, it is much more straight-forward: just update the versions of `@prisma/cli` & `@prisma/client` to `2.5.0-dev.11` and restart Studio.

Let me know what you find.

**Comment by TheBeachMaster** [comment] 2020-08-07 18:21
Hmmm... Seems it's not working for me.... 

I have made thee following changes to `package.json` 

Initially

```json
  "devDependencies": {
    "@prisma/cli": "2.4.1"
  },
  "dependencies": {
    "@prisma/client": "2.4.1"
  }
```

Now updated to

```json
  "devDependencies": {
    "@prisma/cli": "2.4.1"
  },
  "dependencies": {
    "@prisma/client": "2.4.1"
  },
  "resolutions": {
    "@prisma/cli": "2.5.0-dev.11",
    "@prisma/client": "2.5.0-dev.11",
    "@prisma/sdk": "2.5.0-dev.11"
 }
```


Running `npx prisma studio` yields this

```
> prisma@1.0.0 prisma:studio /Users/[redacted]/[redacted]/[redacted]/prisma
> DATABASE_URL="postgresql://[redacted]:[redacted]@127.0.0.1:5432/[redacted]?schema=[redacted]" npx prisma studio --experimental

Environment variables loaded from prisma/.env
Generating Prisma Client ... done
Studio started at http://localhost:5555
Error in request:  PrismaClientInitializationError: Query engine exited with code 1

error: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context
        Did you mean --enable-playground?
USAGE:
    query-engine-darwin --enable-playground
For more information try --help
    at PrismaClientFetcher.request (/Users/[redacted]/.cache/prisma/studio/Users-[redacted]-[redacted]-prisma/runtime/index.js:1:211356)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  query: 'Promise.all([\n' +
// ... [REDACTED]
 +
    '])'
}

```

And `http://localhost:5555/` gives this

![Screenshot 2020-08-07 at 21 18 34](https://user-images.githubusercontent.com/9129843/89676040-9bc12380-d8f3-11ea-8d91-e90e170066a0.png)

**Comment by TheBeachMaster** [comment] 2020-08-07 18:27
Also something I have noticed;

Exiting out of the console and going back to the Prisma Studio page on the browser, you'll see your models but all will have no data

![Screenshot 2020-08-07 at 21 26 08](https://user-images.githubusercontent.com/9129843/89676695-bd6eda80-d8f4-11ea-9c04-d861d8251ca0.png)

**Comment by TheBeachMaster** [comment] 2020-08-07 18:29
@madebysid ,

What is this `query-engine-darwin --enable-playground` it's complaining about... Could there be sone clues here

```
Error in request:  PrismaClientInitializationError: Query engine exited with code 1

error: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context
        Did you mean --enable-playground?
USAGE:
    query-engine-darwin --enable-playground
```

**Comment by tommypater** [comment] 2020-08-07 20:59
@madebysid yarn resolutions resolve my faulty project with "Studio version 0.246.0" in the DevTools console =)

**Comment by TheBeachMaster** [comment] 2020-08-07 21:08
@madebysid Thanks for the response.

Yes I am using Yarn `v1.22.4` on `Node 12.6.0` (initially)

A couple of interesting things I noticed: 

1. Removing resolutions from `package.json` does not do anything other than create the `.prisma/client` files. Studio does not start in this case. Adding resolutions at least starts studio.

2. Following up from the above setup (1) , and viewing the console  I see the following: 
```
Websocket not open. Queueing this request: {"requestId":0,"channel":"photon","action":"start","payload":{"data":null}}
Studio version 0.245.0
Socket connection established
...

[BootstrapStore.init] Studio bootstrap failed ...//.. {stack : "TypeError: Cannot read property 'response' of null
    at er.init (http://localhost:5555/studioBundle.js:395:155579)" }
```
Switching to `Node v14.1.0` and removing `resolutions` at least starts up studio but still fails. Studio version is still `Studio version 0.245.0`

**Comment by madebysid** [comment] 2020-08-10 09:44
@tommypater Ah great, perhaps a few other people who were seeing this can try updating their `@prisma/cli` version as well? If this works for others too, I can close.

@TheBeachMaster Since you're still seeing Studio version 0.245.0, it means `@prisma/cli` didn't actually get updated to `2.5.0-dev.11`. Are you sure you didn't see any issues when you ran `npm i` after changing the versions in your `package.json`? If all else fails, I suppose you can delete your `node_modules` folder, then `npm i` again (making sure `package.json`'s `@prisma/cli` version is `2.5.0-dev.11` or higher)?

**Comment by TheBeachMaster** [comment] 2020-08-14 12:00
This hasn't worked for me. I'll wait for the next update.

**Comment by TheBeachMaster** [comment] 2020-08-29 09:39
This seems to have been fixed in the `2.5.1` update.

**Comment by madebysid** [comment] 2020-08-29 12:33
I'm going to go ahead and close this, but if anyone else runs into it, please let me know so I can reopen!

**Closed by madebysid** 2020-08-29 12:33 UTC
Labels: bug/1-repro-available, kind/regression

**Comment by lewebsimple** [comment] 2020-10-18 18:38
@madebysid I get the same error with 2.9.0 under OSX.

**Comment by madebysid** [comment] 2020-10-19 10:02
@lewebsimple Could you check to make sure you're not running a global installation of prisma 1 by any chance?
Additionally, `--experimental` is no longer needed for `npx prisma studio` (since 2.7.0), so perhaps try updating as well?

**Comment by spcfdoho** [comment] 2020-11-05 09:13
I had the same issue, but when i ran **`prisma studio`** with **sudo**  it worked like a charm.

**Comment by guillaumeLamanda** [comment] 2020-11-29 13:37
I encountered the issue with the following version :  
```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.9.0
@prisma/client       : 2.9.0
Current platform     : darwin
Query Engine         : query-engine 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.296.0
```

The message posted by @spcfdoho made me on the path : *deleting prisma cache folder solved the issue for me*.  
Seem's like a version conflict.

**Comment by Xample** [comment] 2021-05-10 12:08
just my 2 cents: in `package.json, please make sure the version of "@prisma/client" in`dependencies` matches the one of "prisma" in `devDependencies`

I had
```js
{
  "dependencies": {
    "@prisma/client": "^2.22.1",
  },
  "devDependencies": {
    "prisma": "^2.21.1", // <- error, must be the same as @prisma/client i.e. "^2.22.1"
  }
}
```
And got the error above.

**Comment by carchrae** [comment] 2021-06-09 20:04
i just tried to upgrade to 2.24, then tried to roll it back to 2.21 and encountered this error.  at first, i deleted package-lock.json thinking that was the issue, but that did not change anything.  

i suspect it was using `"prisma": "^2.21.2",`  vs `"prisma": "2.21.2",`  - locking it to the specific version (no `^`) seemed to resolve it.  (of course, i did the same thing with `@prisma/client`)

i wiped node_modules in all cases.

**Comment by carchrae** [comment] 2021-06-09 20:06
actually, looking at this, the same error came from somewhere else

```
> npx prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Schema parsing
error: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context
	Did you mean --enable-playground?

USAGE:
    query-engine-debian-openssl-1.1.x --enable-playground

For more information try --help
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by madebysid** [comment] 2021-06-10 07:53
It looks like you somehow have an old version of the query engine in there (that's where the `--enable-playground` flag comes from). If you see it again, can you run `npx prisma -v` and post results here?

Either way, I think just nuking node_modules might have fixed it.
