### ISSUE TITLE
Error in generated query: Provided Int, expected String

### ISSUE THREAD

**Issue by schickling** [prisma/studio#170] opened 2019-09-28 12:33 UTC
![image](https://user-images.githubusercontent.com/1567498/65816506-d438a100-e1fc-11e9-99d2-afe7fb785ea8.png)

Repro: https://github.com/nikolasburk/datasets/tree/northwind/datasets/sqlite/northwind

**Comment by madebysid** [comment] 2019-10-01 08:40
@schickling Using the schema you provided, I was able to reproduce this and I believe the generated query is correct. Created https://github.com/prisma/photonjs/issues/241 for it.

I don't think after should be a string here, since `order_id` is an int. Will wait to see what the result of that issue is before I jump into this!

**Comment by madebysid** [comment] 2019-10-17 16:44
This should now be fixed with alpha.254

**Closed by madebysid** 2019-10-17 16:44 UTC
Labels: bug/1-repro-available, impact/high, kind/bug
