### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by williamluke4** [prisma/studio#477] opened 2020-07-27 12:16 UTC
1. Prisma2 version (`prisma -v`):
```
C:\Users\willi\Documents\X\Projects\prisma2-test>npx prisma -v
Environment variables loaded from prisma\.env
@prisma/cli          : 2.3.0
Current platform     : windows
Query Engine         : query-engine e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules\@prisma\cli\prisma-fmt-windows.exe)
```
2. Logs from Developer Tools Console, if any:
```
C:\Users\willi\Documents\X\Projects\prisma2-test>npx prisma studio --experimental
Environment variables loaded from prisma\.env
Generating Prisma Client ... done
Studio started at http://localhost:5555
npm[23136]: c:\ws\src\node_http_parser_impl.h:429: Assertion `args[0]->IsInt32()' failed.
 1: 00007FF6AECB041F napi_wrap+102143
 2: 00007FF6AEC5EA06 uv_loop_fork+44230
 3: 00007FF6AEC5ED23 uv_loop_fork+45027
 4: 00007FF6AEC490EC v8::internal::UnoptimizedCompilationInfo::feedback_vector_spec+159500
 5: 00007FF6AF23C0A9 v8::internal::OFStreamBase::xsputn+5065
 6: 00007FF6AF23B276 v8::internal::OFStreamBase::xsputn+1430
 7: 00007FF6AF23B8E2 v8::internal::OFStreamBase::xsputn+3074
 8: 00007FF6AF23B73D v8::internal::OFStreamBase::xsputn+2653
 9: 00007FF6AF7F3916 v8::internal::NativesCollection<0>::GetScriptsSource+660214
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
**YES**
4. Prisma2 schema (if relevant):
**PRIVATE**

**Comment by madebysid** [comment] 2020-07-28 09:49
Oh, interesting, this seems to be coming from Node itself (?) Are you able to start an HTTP server in general? (In your own script I mean)

**Comment by williamluke4** [comment] 2020-07-28 09:59
Yeah the same error occurs when running the folowing
```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
async function main(){  
  const f = await prisma.users.findMany()
  console.log(f)
}
main()
```

**Comment by madebysid** [comment] 2020-07-28 10:07
@williamluke4 Oh I meant just a regualr HTTP server. I have a feeling this isn't related to Prisma. Could you try this script out?

```
const http = require("http");

const server = http.createServer((req, res) => {
  res.write("Hello!");
  res.end();
});
server.on("clientError", (err, socket) => {
  socket.end("HTTP/1.1 400 Bad Request\r\n\r\n");
});
server.listen(8000);
```

It'll start an HTTP server (or error out)

If it does error out, perhaps try reinstalling Node?

**Comment by williamluke4** [comment] 2020-07-28 10:54
@madebysid HTTP Server worked fine.
I was using Node **v12.0.0** just Upgraded to **v14.6.0** and the issue went away :)

**Comment by madebysid** [comment] 2020-07-28 10:55
Super weird, but glad it is resolved!

**Comment by mattwelke** [comment] 2020-10-10 16:16
Just ran into this today too. I use `n` and did my usual `n lts` before trying out the quickstart since I like to be on latest LTS always for personal projects (for work projects I sometimes need to `n <some_old_version>`. Got this error. Switching to `n latest` worked for me too (it gave me `14.13.1` today).

**Comment by williamluke4** [comment] 2020-10-11 08:39
@madebysid This is something we should look in to

**Comment by madebysid** [comment] 2020-10-12 12:03
@mattwelke I don't think Node 14+ should be required, this sounds liek a bug. I'll try and reproduce this with Node 12 and see what I find!

**Comment by mattwelke** [comment] 2020-10-13 15:33
@madebysid Sounds good. Here's some more info if it helps:

```
~ > lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

~ > uname -a
Linux mdesk 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by madebysid** [comment] 2020-10-14 12:04
Hey @mattwelke, Node 12.9 broke something in Prisma Client (that Studio uses internally) that I believe was causing this (https://github.com/prisma/prisma-client-js/issues/907). I just tried reproducing this with Node `12.9.0` & Prisma CLI `2.9.0` (released yesterday), and can no longer see this, could you try updating as well?

**Comment by madebysid** [comment] 2020-10-23 14:16
@mattwelke Going to close this, but if you do see this with the latest CLI, let me know, I'll reopen!

**Closed by madebysid** 2020-10-23 14:16 UTC
Labels: bug/0-needs-info, kind/bug
