### ISSUE TITLE
Fatal error: Cannot open cursor to perform index gets in database

### ISSUE THREAD

**Issue by joulev** [prisma/studio#1055] opened 2022-11-19 07:34 UTC
### Bug description

When I open `prisma studio`, a fatal error modal shows up with the following details

```
Cannot open cursor to perform index gets in database
undefined
```

<img width="486" alt="image" src="https://user-images.githubusercontent.com/44609036/202839999-245e42b3-9439-4075-9e89-a51a71dd897c.png">

### How to reproduce

I'm actually not sure how to reproduce, since I'm learning Prisma and MySQL myself... But one thing is that I added a few `@@unique` to my models, then `pnpx prisma db push`-ed successfully, but then `pnpx prisma studio` fails.

### Expected behavior

Studio launching normally. Since all other `prisma` operations work fine without errors, that means I didn't mess up my database somehow right...?

### Prisma information

```yaml
prisma                  : 4.6.1
@prisma/client          : 4.6.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at...)
Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at...)
Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at...)
Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at...)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
Studio                  : 0.476.0
Preview Features        : referentialIntegrity
```

### Environment & setup

- OS: macOS Ventura
- Browser: Safari
- Database: MySQL [PlanetScale]

### Prisma logs

<img width="601" alt="image" src="https://user-images.githubusercontent.com/44609036/202840193-00598147-c5a6-4ac4-a931-b2449c15c3ef.png">

**Comment by joulev** [comment] 2022-11-19 07:43
... and after spamming "Force reload" and "Reload" for five or six times, it suddenly worked for some reasons.

**Comment by petradonka** [comment] 2022-11-21 09:14
Hey @joulev - this looks like a temporary [issue](https://github.com/WebKit/WebKit/blob/0989933dce571efb250060e4cc47d5c952fbf917/Source/WebCore/Modules/indexeddb/server/SQLiteIDBBackingStore.cpp#L2353) in your browser, so I'll close this as it seems to be resolved for you now and it can't be reproduced. Let us know if you run into any further issues!

**Closed by petradonka** 2022-11-21 09:14 UTC
Labels: kind/bug
