### ISSUE TITLE
Getting "Unknown field for select statement" in Prisma Studio for one to many relationships

### ISSUE THREAD

**Issue by jonatns** [prisma/studio#414] opened 2020-05-01 21:35 UTC
## Bug description

I created a one to many relationship between User and Farm. When I run `prisma studio --experimental` prisma studio throws an error after starting up:

<img width="1297" alt="Screen Shot 2020-05-01 at 2 24 22 PM" src="https://user-images.githubusercontent.com/5847682/80842976-e1b17180-8bb7-11ea-9df7-b8ec86dc6436.png">

## How to reproduce

1. Create a one to many relationship like the one described [here](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#overview)
2. Run `prisma migrate save --experimental`
3. Run `prisma migrate up --experimental`
4. Run `prisma generate`
5. Start prisma studio using: `prisma studio --experimental`

## Expected behavior

Prisma studio should start correctly without any errors

## Prisma information
schema:

```javascript
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id          String   @default(uuid()) @id
  auth0Id     String   @unique
  email       String   @unique
  firstName   String
  lastName    String
  phoneNumber String
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  farms       Farm[]
}

model Farm {
  id        String   @default(uuid()) @id
  name      String
  verified  Boolean  @default(false)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  owner     User     @relation(fields: [ownerId], references: [id])
  ownerId   String
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.4
- Node.js version: 12.16.1

**Comment by madebysid** [comment] 2020-05-05 12:51
Hey @jonatn & @kunovsky, thanks for letting me know! I was able to see an error on beta.4, but not on 2.0.0-alpha.1187. I used the schema @jonatns used. Could you try updating and see if this is still happening?

In case it does, any logs in the browser's DevTools Console & your Terminal would be useful as well, thank you!

**Comment by samrith-s** [comment] 2020-05-09 13:25
I am getting the same error for too many fields. Studio is almost unusable right now.
```
Error in Prisma Client request: 

Error: 
Unknown field `displayName` for select statement on model Team.
Unknown field `ownerId` for select statement on model Team. Did you mean `owner`?
    at Document.validate (/Users/sam/.cache/prisma/studio/Users-sam-Work-troup-server/runtime/index.js:1:123114)
    at Object.s [as Team] (/Users/sam/.cache/prisma/studio/Users-sam-Work-troup-server/runtime/index.js:1:82643)
    at Object.n.(anonymous function).n [as findMany] (/Users/sam/.cache/prisma/studio/Users-sam-Work-troup-server/runtime/index.js:1:84025)
    at eval (eval at Photon.request (/Users/sam/Work/troup/server/node_modules/@prisma/cli/build/index.js:2:2178923), <anonymous>:5:50)
    at Photon.request (/Users/sam/Work/troup/server/node_modules/@prisma/cli/build/index.js:2:2179112)
    at PhotonService.respond (/Users/sam/Work/troup/server/node_modules/@prisma/cli/build/index.js:2:420035)
    at WebSocket.StudioServer.onWSMessage (/Users/sam/Work/troup/server/node_modules/@prisma/cli/build/index.js:2:2857610)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.EventEmitter.emit (domain.js:448:20)
    at Receiver.receiverOnMessage (/Users/sam/Work/troup/server/node_modules/@prisma/cli/build/index.js:2:1563673)
```

**Version**
@prisma/cli          : 2.0.0-beta.4
Current platform     : darwin
Query Engine         : query-engine afd294205618b1c825b013ba6f5a6ebe4aa4a514
Migration Engine     : migration-engine-cli afd294205618b1c825b013ba6f5a6ebe4aa4a514
Introspection Engine : introspection-core afd294205618b1c825b013ba6f5a6ebe4aa4a514

**Comment by madebysid** [comment] 2020-05-09 13:42
Super strange. It seems these fields don't exist in your database.

Just to be 100% sure, are you guys migrating your databases after changing your schema?
Studio doesn't migrate your database for you, you'll have to run `prisma migrate save --experimental && prisma migrate up --experimental` on your own.

There should be a log in the browser's DevTools Console that shows you the exact prisma query Studio sent out. Can you run that query in a standalone script and see if you get the same error?

Here's what that script might look like:
```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const main = async () => {
  console.log(await prisma.user.findMany( ... )) // Replace this with the query you found.
}

main()
  .catch(async (e) => console.log(e))
  .finally(async () => await prisma.disconnect())
```

**Comment by kunovsky** [comment] 2020-05-09 13:54
Hey @madebysid - sorry for the delay. I'm actually using `nexus@0.21.0-next.21` and `nexus-plugin-prisma@0.8.0-next.8` so I'm not sure I'm going to be able to bump to `alpha.1187` quite yet, unless I can manually add Prisma...  I just feel like that might be an anti-pattern.

In answer to your question, are you running `prisma migrate save --experimental && prisma migrate up --experimental`, yeah those commands are being executed. 

Note that if I migrate and then seed my DB with data with the `nexus-plugin-prisma@0.8.0-next.8` (which is using `2.0.0-beta.4` under the hood), and then downgrade to a version of `nexus-plugin-prisma` that is using a version of Prisma prior to `2.0.0-beta.4` and run the `prisma studio --experimental` command, it's able to connect to the DB fine, and I can verify that the DB has the all the correct relations and data that I seeded.

Sorry I can't be more help with the `2.0.0-alpha.1199`

**Comment by samrith-s** [comment] 2020-05-09 14:00
Hey @madebysid I am running the migrations. This is the result of `prisma migrate up --experimental`

```prisma
🏋️‍  migrate up

Datamodel that will initialize the db:

datasource db {
  provider = "postgresql"
  url = "***"
}

generator client {
  provider = "prisma-client-js"
}

model Team {
  id          Int      @default(autoincrement()) @id
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  maxMembers  Int      @default(25)
  name        String   @unique
  displayName String?
  adminEmail  String?
  owner       User     @relation(fields: [ownerId], references: [id])
  ownerId     Int
  members     User[]   @relation("_UsersOnTeam", references: [id])
}

model User {
  id          Int         @default(autoincrement()) @id
  createdAt   DateTime    @default(now())
  updatedAt   DateTime    @updatedAt
  email       String      @unique
  password    String
  profile     UserProfile
  memberTeams Team[]      @relation("_UsersOnTeam")
  ownerTeams  Team[]
}

model UserProfile {
  id                     Int      @default(autoincrement()) @id
  createdAt              DateTime @default(now())
  updatedAt              DateTime @updatedAt
  firstName              String
  lastName               String
  isSuperAdmin           Boolean  @default(false)
  professionalCompetence String?
  utm_source             String?
  utm_campaign           String?
  utm_medium             String?
  utm_term               String?
  utm_content            String?
  user                   User     @relation(fields: [userId], references: [id])
  userId                 Int
}


Checking the datasource for potential data loss...

Database Changes:

Migration            Database actions           Status

20200509151001-init  4 CreateTable statements.  Done 🚀

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md

🚀    Done with 1 migration in 335ms.
```

Also, this is the script I ran as you suggested:
```ts
import { PrismaClient } from '@prisma/client';
import { config } from 'dotenv';

config();

const prisma = new PrismaClient();

const main = async () => {
    console.log(
        await prisma.team.findMany({
            first: 100,
            select: {
                id: true,
                createdAt: true,
                updatedAt: true,
                maxMembers: true,
                name: true,
                displayName: true,
                adminEmail: true,
                owner: true,
                ownerId: true,
                members: true,
            },
        })
    );
};

main()
    .catch(async e => console.log(e))
    .finally(async () => await prisma.disconnect());
```

Which in turn, logged this:
```zsh
[ { id: 1,
    createdAt: 2020-05-09T13:19:36.868Z,
    updatedAt: 2020-05-09T13:19:36.869Z,
    maxMembers: 25,
    name: 'team-9',
    displayName: null,
    adminEmail: null,
    owner:
     { id: 1,
       createdAt: 2020-05-09T13:19:36.868Z,
       updatedAt: 2020-05-09T13:19:36.869Z,
       email: 'samrith_9@me.com',
       password:
        '$2a$10$2m51EAEXZatheR1kR409v.gj1Ax0fDzAb7sjFDAl7Q4WTdI8zzGxO' },
    ownerId: 1,
    members: [] } ]
```

As for `.alpha-1199`, it works! I will post an update if I encounter it again.

**Comment by madebysid** [comment] 2020-05-09 14:07
@kunovsky Ah no worries, the fact that you can see the correct data in an older version of Prisma (& Studio) is already helpful. Do you have a repository I can check out? If not, I'll try and reproduce your setup. Your schema (and change you made) might be helpful in that case. I'm fairly certain that it should happen with any schema, but it doesn't hurt to have extra info!

> unless I can manually add Prisma... I just feel like that might be an anti-pattern.
Yep you're correct, you shouldn't need to manually add Prisma.

@samrith-s Awesome, so it indeed looks like I broke something on beta.4.

**Comment by samrith-s** [comment] 2020-05-09 14:11
I have manually added Prisma Client and Prisma CLI on top of my Nexus. I didn’t understand how to use Nexus to serve my server. 

I know it’s off topic, but can you provide a link to some resource? The documentation didn’t help much.

**Comment by madebysid** [comment] 2020-05-09 14:18
@samrith-s Not sure if I inderstood you correctly, but have you taken a look at the Prisma plugin for Nexus? https://nexus.js.org/docs/nexus-prisma? To be honest, I haven't ever really used Nexus, so I might not be the right person to ask 😅
You might want to start a discussion over at https://github.com/prisma/prisma/discussions if you're feeling lost!

**Comment by kunovsky** [comment] 2020-05-09 15:51
@madebysid yeah for sure - if you want I can add you as a guest to our GitLab repo? Not seeing `madebysid` as a user there, can you ping me your username?

**Comment by madebysid** [comment] 2020-05-09 15:58
@kunovsky Oh yeah that'd be helpful. Looks like I had a really old account on GitLab. My username on there is the same now: https://gitlab.com/madebysid

**Comment by kunovsky** [comment] 2020-05-09 16:06
@madebysid - sweet, invite sent. Thanks for the help and let me know if you have any questions getting up and running. Happy to answer them.

**Comment by madebysid** [comment] 2020-05-13 11:16
Hey @kunovsky, I was just trying to clone your repo, and it turns out I'm not allowed to download code from that project. I'm not super familiar with GitLab, maybe I need higher clearance?

If that isn't possible, just your schema should give me a starting point, and you can perhaps send it over to me on our [public Slack](https://slack.prisma.io/). My username on there is `@siddhant`

I also tried the OP's schema on beta.5 (just release yesterday), and was able to load it up fine, so it might be worth trying to update. Things are always changing, so I might have already fixed this :D

**Comment by madebysid** [comment] 2020-05-14 12:25
For everyone here, @kunovsky & I had a chat, and it looks like their issue was a bug with self relations: https://github.com/prisma/prisma/issues/2442

If you want to check if this affects you too, here's how: Studio logs every Prisma Client query it sends to the browser's Devtools Console. So if you take the query that is failing and put it in one of your resolvers, it *should* crash in the same way.
If https://github.com/prisma/prisma/issues/2442 looks similar to the error you get, then it might be worth following that issue.

I'm going to close this one, since it doesn't look like I can do anything here given that the error seems to be originating from Client, but please do let me know if you think otherwise, and this can be reopened.

**Closed by madebysid** 2020-05-14 12:25 UTC
Labels: bug/0-needs-info, kind/bug
