### ISSUE TITLE
Prisma Studio : "Failed to run script"

### ISSUE THREAD

**Issue by HubnerJonathan** [prisma/studio#291] opened 2019-11-18 16:09 UTC
Hi,

I'm new to the prisma framework. When I try to use prisma studio (by default on http://localhost:5555/) this error appears. I can still use studio and navigate into the different tables of my DB but they appear empty.

`Error in Photon: 
Error: undefined target="exit" timestamp="2019-11-18T15:40:41.176Z" fields={"message":"255"}
    at /home/avalon/.nvm/versions/node/v12.2.0/lib/node_modules/prisma2/build/index.js:338787:27
    at processTicksAndRejections (internal/process/task_queues.js:89:5)`

I'm using Ubuntu 18.04.3.

BR,

**Comment by madebysid** [comment] 2019-11-20 18:46
@HubnerJonathan Could you try out the latest alpha (alpha.337) with `npm i -g prisma2@alpha` and let me know if you still see this? Thanks!

**Comment by HubnerJonathan** [comment] 2019-11-26 13:25
Hey,

Just did it and the error changed. I've now got : 
`Cannot destructure property `dmmf` of 'undefined' or 'null'.
TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at connect (/home/avalon/.nvm/versions/node/v12.2.0/lib/node_modules/prisma2/build/photon-worker.js:44:11)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async process.<anonymous> (/home/avalon/.nvm/versions/node/v12.2.0/lib/node_modules/prisma2/build/photon-worker.js:9:18)`

**Comment by madebysid** [comment] 2019-11-26 13:40
Hmm I don't see this so it looks like something specific to your project. From the logs, it looks like Studio was unable to generate photon (that it uses internally). 
Are you also able to use photon via a normal script?

Also, have you taken a look at the latest preview/alpha's breaking change: https://github.com/prisma/prisma2/releases/tag/2.0.0-preview017

Specifically, you now need `@prisma/photon` as a dependency to your project.

If you can upload your project as a GH repository and link it here, I can try to reproduce and figure out what's going wrong. Thanks!

**Comment by HubnerJonathan** [comment] 2019-11-26 13:58
I have the same error when I try to create a new prisma repository.

- npx prisma2 init "myrepo" (graphql + auth project)
- cd "myrepo"
- npm install prisma2 --save-dev
- npm install @prisma/photon
- npx prisma2 dev

Do I do something wrong ?

BR.

**Comment by madebysid** [comment] 2019-11-26 16:22
@HubnerJonathan This is super weird, I just did the same thing on a Mac, didn't see this, but I tried it on an Ubuntu Virtual Machine and can now reproduce this. I'll figure out what's happening in a bit and get back to you here.

**Comment by madebysid** [comment] 2019-11-28 14:14
Hello @HubnerJonathan! We just pushed out 2.0.0-preview017.2, which has a fix for this problem. It was indeed a Linux specific issue. I've also verified that Studio now works on my virtual machine.
In case you do not want to `prisma2 init` another project, you can just bump up versions of `prisma2` and `@prisma/photon` to `latest`, `npm i` and try again. Please let me know if you're still running into issues!

**Comment by madebysid** [comment] 2019-12-03 17:45
Going to close this, but please reopen if you're still running into issues!

**Closed by madebysid** 2019-12-03 17:45 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by viniciussolique39** [comment] 2024-10-20 02:21
Hi community, 

I need your help, when I run the command "npx prisma studio" in the VSCode terminal I am directed to localhost and the following message appears: 
"Prisma Client Error"

Unable to run script    

show details

Error message attachment.


Message: Error in Prisma Client request: 


Invalid `p=e.match(jAt)?.[1]??"",g=e.match(BAt)?.[1]??null,v=e.match(UAt)?.[1]??null,{getPrismaClient:x,PrismaClientKnownRequestError:E,PrismaClientRustPanicError:D,PrismaClientInitializationError:P,PrismaClientValidationError:R}=require(`${u.prismaClient}/runtime/${c}`),k=e,F=(0,Mj.createHash)("sha256").update()` invocation in
C:\API\node_modules\prisma\build\index.js:1935:10404

  1932       }
  1933     }
  1934   }
→ 1935 `}});return Xe.resourceList(a.workspaces)}};var CAe=require("@prisma/engines");var iDe=require("buffer");function sDe(e,r,n,i){Object.defineProperty(e,r,{get:n,set:i,enumerable:!0,configurable:!0})}var aDe={};sDe(aDe,"serializeRPCMessage",()=>tq);sDe(aDe,"deserializeRPCMessage",()=>rq);var Z5="PrismaBigInt::",eq="PrismaBytes::";function tq(e){return JSON.stringify(e,(r,n)=>typeof n=="bigint"?Z5+n:n?.type==="Buffer"&&Array.isArray(n?.data)?eq+iDe.Buffer.from(n.data).toString("base64"):n)}function rq(e){return JSON.parse(e,(r,n)=>typeof n=="string"&&n.startsWith(Z5)?BigInt(n.substr(Z5.length)):typeof n=="string"&&n.startsWith(eq)?n.substr(eq.length):n)}var yAe=B(dDe()),bT=B(sAe()),bAe=B(require("http")),xAe=B(cAe()),wAe=require("zlib");var To=require("path");var Mj=require("crypto"),hAe=B(kj());function Lj(e,r,n,i){Object.defineProperty(e,r,{get:n,set:i,enumerable:!0,configurable:!0})}var mAe=globalThis,Fj={},yT={},Dp=mAe.parcelRequire1308;Dp==null&&(Dp=function(e){if(e in Fj)return Fj[e].exports;if(e in yT){var r=yT[e];delete yT[e];var n={id:e,exports:{}};return Fj[e]=n,r.call(n.exports,n,n.exports),n.exports}var i=new Error("Cannot find module '"+e+"'");throw i.code="MODULE_NOT_FOUND",i},Dp.register=function(r,n){yT[r]=n},mAe.parcelRequire1308=Dp);var gAe=Dp.register;gAe("9lTzd",function(module,exports){Lj(module.exports,"guessEnginePaths",()=>guessEnginePaths),Lj(module.exports,"guessPrismaClientPath",()=>guessPrismaClientPath);var $5COlq=Dp("5COlq");async function guessEnginePaths({forceBinary,forceLibrary,resolveOverrides}){let queryEngineName,queryEngineType;if(forceLibrary?(queryEngineName=await(0,$5COlq.prismaEngineName)("query-engine","library"),queryEngineType="library"):forceBinary?(queryEngineName=await(0,$5COlq.prismaEngineName)("query-engine","binary"),queryEngineType="binary"):(queryEngineName=void 0,queryEngineType=void 0),!queryEngineName||!queryEngineType)return{queryEngine:void 0};let queryEnginePath;if(resolveOverrides[".prisma/client"])queryEnginePath=(0,To.resolve)(resolveOverrides[".prisma/client"],`../${queryEngineName}`);else if(resolveOverrides["@prisma/engines"])queryEnginePath=(0,To.resolve)(resolveOverrides["@prisma/engines"],`../../${queryEngineName}`);else{let atPrismaEnginesPath;try{atPrismaEnginesPath=eval("require.resolve('@prisma/engines')")}catch(e){throw new Error("Unable to resolve Prisma engine paths. This is a bug.")}queryEnginePath=(0,To.resolve)(atPrismaEnginesPath`../../${queryEngineName}`)}return{queryEngine:{type:queryEngineType,path:queryEnginePath}}}function guessPrismaClientPath({resolveOverrides}){let prismaClientPath=resolveOverrides["@prisma/client"]||eval("require.resolve('@prisma/client')");return(0,To.resolve)(prismaClientPath,"../")}});gAe("5COlq",function(e,r){Lj(e.exports,"prismaEngineName",()=>n);async function n(i,a){let o=await Hr(),c=o==="windows"?".exe":"";if(a==="library")return qa(o,"fs");if(a==="binary")return`${i}-${o}${c}`;throw new Error(`Unknown engine type: ${a}`)}});function qAt(e){return{models:$j(e.models),enums:$j(e.enums),types:$j(e.types)}}function $j(e){let r={};for(let{name:n,...i}of e)r[n]=i;return r}var sx=(0,hAe.debug)("prisma:studio-pcw"),jAt=/^\s*datasource\s+([^\s]+)\s*{/m,BAt=/url *= *env\("(.*)"\)/,UAt=/url *= *"(.*)"/;async function GAt({schema:e,schemaPath:r,dmmf:n,datasourceProvider:i,previewFeatures:a,datasources:o,engineType:c,paths:u,directUrl:l,versions:f}){let p=e.match(jAt)?.[1]??"",g=e.match(BAt)?.[1]??null,v=e.match(UAt)?.[1]??null,{getPrismaClient:x,PrismaClientKnownRequestError:E,PrismaClientRustPanicError:D,PrismaClientInitializationError:P,PrismaClientValidationError:R}=require(`${u.prismaClient}/runtime/${c}`),k=e,F=(0,Mj.createHash)("sha256").update(
Error converting field "age" of expected non-nullable type "String", found incompatible value of "null".
  
Query:
{
  "modelName": "User",
  "operation": "findMany",
  "args": {
    "take": 100,
    "skip": 0,
    "select": {
      "id": true,
      "email": true,
      "name": true,
      "age": true
    }
  }
}
  

I'm waiting. 

Thanks. 

BR.
