### ISSUE TITLE
Unable to process `count` query undefined

### ISSUE THREAD

**Issue by sir-guevara** [prisma/studio#1067] opened 2022-12-19 08:39 UTC
### Bug description

A non-recoverable error has occurred. Reload Studio to continue. Consider reporting this error to us by opening an issue on GitHub and attaching the error details.
Unable to process `count` query
undefined

### Environment & setup

- OS: 
- Browser: 
- Database:

**Comment by petradonka** [comment] 2023-01-03 17:09
It looks like this is a duplicate of https://github.com/prisma/studio/issues/890, so closing this issue.

**Closed by petradonka** 2023-01-03 17:09 UTC
Labels: kind/bug
