### ISSUE TITLE
Expected object to have exactly 1 key-value pairs, got: 3

### ISSUE THREAD

**Issue by sachaw** [prisma/studio#386] opened 2020-03-17 12:46 UTC
Prisma 2.0.0-preview024

Appears to happen If I update certain fields or relations, some tables are unaffected.

```
Error in request:  {
  telemetry: false,
  message: '\n' +
    'Invalid `prisma.user.create()` invocation:\n' +
    '\n' +
    'Failed to validate the query `Error occurred during query validation & transformation:\n' +
    'Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (id, name).` at ``',
  stack: 'Error: \n' +
    'Invalid `prisma.user.create()` invocation:\n' +
    '\n' +
    'Failed to validate the query `Error occurred during query validation & transformation:\n' +
    'Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (id, name).` at ``\n' +
    '    at PrismaClientFetcher.request (/home/sachaw/.cache/prisma/studio/home-sachaw-api/runtime/index.js:1:47358)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  isPanic: undefined,
  code: 'P2009'
} {
  query: 'prisma.user.create(\n' +
    '{\n' +
    '  "data": {\n' +
    '    "activated": true,\n' +
    '    "username": "sachaw",\n' +
    '    "name": "Sacha Weatherstone",\n' +
    '    "avatar": "data:image/png;base64,iVBORAAASUVORK5CYII=...",\n' +
    '    "password": null,\n' +
    '    "updatedAt": "1970-01-01T00:00:00.000Z",\n' +
    '    "groups": {\n' +
    '      "connect": [\n' +
    '        {\n' +
    '          "id": "ck7vu9d460001cl9tidjt13ij",\n' +
    '          "name": "System"\n' +
    '        },\n' +
    '        {\n' +
    '          "id": "ck7vu9d490002cl9tx13yus51",\n' +
    '          "name": "Admin"\n' +
    '        },\n' +
    '        {\n' +
    '          "id": "ck7vu9d3y0000cl9tsh1abdom",\n' +
    '          "name": "User"\n' +
    '        }\n' +
    '      ]\n' +
    '    }\n' +
    '  },\n' +
    '  "select": {\n' +
    '    "id": true,\n' +
    '    "activationClaim": true,\n' +
    '    "username": true,\n' +
    '    "activated": true,\n' +
    '    "name": true,\n' +
    '    "avatar": true,\n' +
    '    "password": true,\n' +
    '    "createdAt": true,\n' +
    '    "updatedAt": true,\n' +
    '    "groups": true,\n' +
    '    "tokens": true,\n' +
    '    "linkedAccounts": true,\n' +
    '    "userCredentials": true,\n' +
    '    "userActionses": true\n' +
    '  }\n' +
    '}\n' +
    ')'
}
Error in request:  {
  telemetry: false,
  message: '\n' +
    'Invalid `prisma.user.update()` invocation:\n' +
    '\n' +
    'Failed to validate the query `Error occurred during query validation & transformation:\n' +
    'Assertion error: Expected object to have exactly 1 key-value pairs, got: 3 (activationClaim, id, username).` at ``',
  stack: 'Error: \n' +
    'Invalid `prisma.user.update()` invocation:\n' +
    '\n' +
    'Failed to validate the query `Error occurred during query validation & transformation:\n' +
    'Assertion error: Expected object to have exactly 1 key-value pairs, got: 3 (activationClaim, id, username).` at ``\n' +
    '    at PrismaClientFetcher.request (/home/sachaw/.cache/prisma/studio/home-sachaw-api/runtime/index.js:1:47358)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  isPanic: undefined,
  code: 'P2009'
} {
  query: 'prisma.user.update(\n' +
    '{\n' +
    '  "where": {\n' +
    '    "id": "ck7vvu8m800012f9tl9lyefy8",\n' +
    '    "activationClaim": "ck7vvu8m800002f9tdikkblbi",\n' +
    '    "username": "sachaw"\n' +
    '  },\n' +
    '  "data": {\n' +
    '    "groups": {\n' +
    '      "set": [\n' +
    '        {\n' +
    '          "id": "ck7vu9d460001cl9tidjt13ij",\n' +
    '          "name": "System"\n' +
    '        }\n' +
    '      ]\n' +
    '    }\n' +
    '  },\n' +
    '  "select": {\n' +
    '    "id": true,\n' +
    '    "activationClaim": true,\n' +
    '    "username": true,\n' +
    '    "groups": true\n' +
    '  }\n' +
    '}\n' +
    ')'
}
Error in request:  {
  telemetry: false,
  message: '\n' +
    'Invalid `prisma.user.update()` invocation:\n' +
    '\n' +
    'Failed to validate the query `Error occurred during query validation & transformation:\n' +
    'Assertion error: Expected object to have exactly 1 key-value pairs, got: 3 (activationClaim, id, username).` at ``',
  stack: 'Error: \n' +
    'Invalid `prisma.user.update()` invocation:\n' +
    '\n' +
    'Failed to validate the query `Error occurred during query validation & transformation:\n' +
    'Assertion error: Expected object to have exactly 1 key-value pairs, got: 3 (activationClaim, id, username).` at ``\n' +
    '    at PrismaClientFetcher.request (/home/sachaw/.cache/prisma/studio/home-sachaw-api/runtime/index.js:1:47358)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  isPanic: undefined,
  code: 'P2009'
} {
  query: 'prisma.user.update(\n' +
    '{\n' +
    '  "where": {\n' +
    '    "id": "ck7vvu8m800012f9tl9lyefy8",\n' +
    '    "activationClaim": "ck7vvu8m800002f9tdikkblbi",\n' +
    '    "username": "sachaw"\n' +
    '  },\n' +
    '  "data": {\n' +
    '    "name": "Sacha Weatherstone"\n' +
    '  },\n' +
    '  "select": {\n' +
    '    "id": true,\n' +
    '    "activationClaim": true,\n' +
    '    "username": true,\n' +
    '    "name": true\n' +
    '  }\n' +
    '}\n' +
    ')'
}
```

**Comment by madebysid** [comment] 2020-03-17 14:40
@sachaw This is great, thanks for the logs! This seems to be coming from the query engine. Could you also share your schema? (If not the whole thing, then just the problematic model?)

I'll then try and reproduce this!

**Comment by sachaw** [comment] 2020-03-17 21:08
This should be all relevant parts of the schema, thanks in advance:
```
enum TokenUse {
  ACCESS
  REFRESH
}

model User {
  id                    String   @default(cuid()) @id
  activated             Boolean  @default(false)
  activationClaim       String   @default(cuid()) @unique
  username              String   @unique
  name                  String
  avatar                String   @default("data:image/png;base64,iVBOAk7xIwN5CYII=...")
  password              String?
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
  groups                Group[]
  tokens                Token[]
  linkedAccounts        LinkedAccount[]
  userCredentials       UserCredential[]
}

model UserCredential {
  id                    String   @id
  revoked               Boolean  @default(false)
  publicKey             String
  lastUsed              DateTime?
  fidoAAGUID            String
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
  associatedTokens      Token[]
  user                  User
}

model authChallenge {
  id                    String   @default(cuid()) @id
  challenge             String   @unique
  expires               DateTime
}

model Group {
  id                    String   @default(cuid()) @id
  name                  String   @unique
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
  users                 User[]
}

model Token {
  id                    String   @id
  type                  TokenUse
  revoked               Boolean  @default(false)
  lastIp                String?
  lastUserAgent         String?
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
  associatedTokens      Token[]
  userCredential        UserCredential?
  user                  User?
}

enum LinkableService {
  ANILIST
  PLEX
}

model LinkedAccount {
  id                    String   @default(cuid()) @id
  service               LinkableService
  accountId             String   @unique
  accessToken           String
  accessTokenExpires    DateTime?
  refreshToken          String?
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
  user                  User
}
```

**Comment by madebysid** [comment] 2020-03-19 15:43
Hey @sachaw, thanks again for reporting this, it uncovered a bunch of broken things in Studio that are now fixed and out on alpha.936.
I also discovered a bug in the typings of Prisma Client that I've reported here:

@guillaumeLamanda Your schema should be fixed as well.

Let me know if you still see similar issues!

**Closed by madebysid** 2020-03-19 15:43 UTC
Labels: bug/2-confirmed, kind/bug
