### ISSUE TITLE
Prisma Studio does not show existing rows

### ISSUE THREAD

**Issue by jan-wilhelm** [prisma/studio#559] opened 2020-10-02 09:59 UTC
## Bug description
Prisma Studio has seemingly stopped showing some rows in my Postgres Table that do exist in the database, as shown in the screenshot:
![image](https://user-images.githubusercontent.com/16737505/94911415-66295880-04a6-11eb-8c6f-2e7a190d140b.png)

## How to reproduce
I'm really not sure how to reproduce this. I deleted `node_modules` and recreated it. I have also restarted Prisma Studio and my DB.

## Expected behavior
Prisma should show the existing database rows in Prisma Studio.

## Prisma information
I am on Prisma Clien and CLI 2.8.0

## Environment & setup

- OS: macOS Catalina
- Database: PostgreSQL
- Node.js version: v12.6.1
- Prisma version:
```
@prisma/cli          : 2.8.0
Current platform     : darwin
Query Engine         : query-engine e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.294.0
Preview Features     : connectOrCreate, transactionApi
```

**Comment by madebysid** [comment] 2020-10-06 11:14
Hey @jan-wilhelm! Thanks for reporting this, and apologies for the delayed response.

This is super weird. Usually, new rows should show up after you press the refresh button on the left. Restarting Studio should also have the same effect, so I'm a bit stumped.

1. How are you creating these rows? I presume you're creating these rows from your app and are using Studio to check if they were created correctly?
2. Does this happen intermittently or do new rows never show up?
3. If you open up the browser's DevTools, you should be able to see the actual Prisma Client query that went out. Could you show me what that is? (if there's anything about it you want to redact, let me know)

In the mean time, I'm also going to check out Blitz and see if I can reproduce this!

**Comment by jan-wilhelm** [comment] 2020-10-06 12:19
hey @madebysid,

Apparently I didn't know that there was a refresh button and the rows did show up after refreshing. However, I know for a fact that those rows had already been stored in the database before even starting Prisma Studio. It seems like this issue only occurs on initial page load and goes away when refreshing.

Furthermore, I cannot seem to be able to reproduce this issue anymore. I know that this sounds super weird (and I find it weird too), but I think I will close this issue for now and come back to it if it ever occurs again. I know that I did triple-check that the rows were in the database (they were showing up in pgAdmin) but not in Prisma Studio, but the error seems to have gone away now.

:)

**Comment by madebysid** [comment] 2020-10-06 12:32
Huh, only on initial load? I'm fairly certain the same query goes out during the initial load and when you press 'Refresh', so this has confused me more than before :D

No worries though, since you say this is no longer an issue, I'll close this for now, but if you do manage to reproduce it / see it again, please feel free to reopen / create a new issue!

**Closed by madebysid** 2020-10-06 12:32 UTC
Labels: bug/0-needs-info, kind/bug
