### ISSUE TITLE
Cannot create record with prisma and mongodb

### ISSUE THREAD

**Issue by rouzbehsbz** [prisma/studio#771] opened 2021-09-06 06:16 UTC
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma                : 2.30.3
@prisma/client        : 2.30.3
Current platform      : windows
Query Engine (Binary) : query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine      : migration-engine-cli b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine  : introspection-core b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary         : prisma-fmt b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash  : b8c35d44de987a9691890b3ddf3e2e7effb9bf20
Studio                : 0.423.0
Preview Features      : mongoDb
```
2. Logs from Developer Tools Console or Command line, if any:
```
ConnectorError(ConnectorError { user_facing_error: None, kind: RawError { code: "unknown", message: "Command failed (IllegalOperation): This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.)" } })
    at cb (D:\Programming\Coinlocally\binance_mirror\node_modules\@prisma\client\runtime\index.js:36498:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  clientVersion: '2.30.3'
}
```

4. Prisma schema (if relevant):
```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

model post {
  id String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  title String
  body String
}
```

I also tried set `retryWrites=false` to my connection string but still doesn't work:
`DATABASE_URL = "mongodb://localhost:27017/test?retryWrites=false"`

**Comment by madebysid** [comment] 2021-09-07 06:34
Hey @rouzbehsbz, I haven't spent a significant time trying to support MongoDB in Studio just yet, but I'll do that soon. This could very well be a configuration error in Studio. I'll keep you posted.

**Comment by rouzbehsbz** [comment] 2021-09-09 08:49
thanks for your comment, actually its not just the prisma studio that cause that error. I get that error whenever I try to write data to mongoDB using prisma client or prisma studio, and I think there is no problem with my mongoDB because I can use other ORMs without any problem or additional database configurations.

**Comment by madebysid** [comment] 2021-09-09 10:06
Ah, in that case, I'd encourage you to isolate the issue by creating a simple script with only the create and see what happens. 
Are you able to read data?
Also, make sure you have write permissions on the DB instance.

If this continues outside of Studio as well, please do create an issue on https://github.com/prisma/prisma. Since Mongo is still in preview, it might indicate a bug on our end as well :)

**Comment by rouzbehsbz** [comment] 2021-09-09 10:17
I got the `Command failed (IllegalOperation): This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.` error with simple `prisma.post.create()` method.
and yes I'm able to read data from DB. as the error said I tried to add `retryWrites=false` to my connection string as query. but nothing happens. I don't think there is no need to additional mongoDB config as I installed it locally and as is said it works with other ORMs like `mongoose `.

since this error throws from Studio too, I think this issue should be opened as well.
thanks

**Comment by ADRFranklin** [comment] 2021-09-10 11:15
Hi, I am also getting this issue. Though I am using the go client and generator. I'm actually having to have 2 client generators to get prisma to even run, one for generating the go code and the other just using the js client for prisma studio to run. 

But still I face the same issue where creating new data presents me with the same error message. I've tried following the instructions of adding the `retryWrites=false` to the db url env but to no avail. 

I'm assuming this must be an issue with the js-client version that I bet prisma studios also shares, as for the go code I am perfectly able to add/delete/update records without problems.

**Comment by RichardBray** [comment] 2021-11-05 09:58
Has there been any update on this issue? I'm getting the same thing.

**Comment by janpio** [comment] 2021-11-05 11:50
Can you create records with Prisma Client directly or does that also fail? 
If it fails, please open an issue over at https://github.com/prisma/prisma.
If it does not, please provide the information here that we need to try to reproduce what is happening for you please.

**Comment by RichardBray** [comment] 2021-11-05 18:40
@janpio no this issue isn't related to studio it's a general Prisma issue. I'll see if there's an issue there already.

**Comment by xencodes** [comment] 2021-11-10 03:42
any updates?

**Comment by janpio** [comment] 2021-11-10 15:41
Updates to what @xencodes? 
Are you getting errors in Prisma Studio? Then please add them here in this issue - until now no one posted any.
Are you getting errots with Prisma Client? Then please create an (or look for an existing) issue over at https://github.com/prisma/prisma

**Comment by madebysid** [comment] 2021-12-20 14:05
Hey everyone I'm closing this for now since it seems like it was a Prisma Client issue in general, but it should most likely be fixed now.. If you're still unable to work with MongoDB in Studio, please let me know and I will reopen (or perhaps create a new issue!)

**Closed by madebysid** 2021-12-20 14:05 UTC
Labels: bug/1-repro-available, kind/bug, topic: mongodb

**Comment by emimarz** [comment] 2022-03-01 19:32
any news on this issue, the error still happening

**Comment by janpio** [comment] 2022-03-01 20:01
Please open an issue and provide all the information the template is asking for, optimally enough for us to reproduce. Thanks.
