### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by schickling** [prisma/studio#227] opened 2019-10-15 14:54 UTC
![image](https://user-images.githubusercontent.com/1567498/66842876-4387f200-ef6c-11e9-8043-0cc4b59bf3eb.png)

Repro: Go to https://prisma-studio.now.sh/preview?project=chinook and select `Track` model

**Comment by madebysid** [comment] 2019-10-15 15:34
Relevant logs for me:

```
{"error":null,"data":{"error":null,"data":{"error":{"message":"\nInvalid `photon.tracks.findMany()` invocation:\n\n{\n  select: {\n?   id?: true,\n?   name?: true,\n?   album?: true,\n?   mediaType?: true,\n?   genre?: true,\n?   composer?: true,\n?   milliseconds?: true,\n?   bytes?: true,\n?   unitPrice?: true,\n?   invoiveItems?: true,\n    playlistTrack: true,\n    ~~~~~~~~~~~~~\n?   playlistTracks?: true\n  },\n  orderBy: {\n    id: 'asc'\n  },\n  first: 100\n}\n\n\nUnknown field `playlistTrack` for select statement on model Track. Available options are listed in green. Did you mean `playlistTracks`?\n","stack":"Error: \nInvalid `photon.tracks.findMany()` invocation:\n\n{\n  select: {\n?   id?: true,\n?   name?: true,\n?   album?: true,\n?   mediaType?: true,\n?   genre?: true,\n?   composer?: true,\n?   milliseconds?: true,\n?   bytes?: true,\n?   unitPrice?: true,\n?   invoiveItems?: true,\n    playlistTrack: true,\n    ~~~~~~~~~~~~~\n?   playlistTracks?: true\n  },\n  orderBy: {\n    id: 'asc'\n  },\n  first: 100\n}\n\n\nUnknown field `playlistTrack` for select statement on model Track. Available options are listed in green. Did you mean `playlistTracks`?\n\n    at Document.validate (/var/task/node_modules/@generated/photon/chinook/runtime/index.js:2851:23)\n    at TrackClient.get _document [as _document] (/var/task/node_modules/@generated/photon/chinook/index.js:1266:22)\n    at TrackClient.then (/var/task/node_modules/@generated/photon/chinook/index.js:1287:63)"},"meta":{},"response":[]},"requestId":0}}
```

**Comment by madebysid** [comment] 2019-10-17 09:08
After some investigation, it looks like this error is specific to the Chinook dataset. The schema for this dataset came from https://github.com/prisma/prisma-datasets/tree/master/datasets/sqlite/chinook, which was written manually to account for the lack of introspection for SQLite.

Writing it, @nikolasburk realized that prisma2 does not support some kinds of join tables (https://github.com/prisma/prisma2/issues/773). So while the photon generation itself works, the underlying DMMF (the AST we use for the schema) is wrong. This means that the query that Studio generated for fetching Tracks is wrong, which means this request fails.

Specifically, the issue is with the `PlaylistTrack` model:
```
model PlaylistTrack {
  id       String   @id @default(cuid())
  playlist Playlist @map("PlaylistId")
  track    Track    @map("TrackId")

  @@map("playlist_track")
}

model Playlist {
  id   Int     @id @map("PlaylistId")
  name String? @map("Name")

  @@map("playlists")
}

model Track {
  id           Int           @id @map("TrackId")
  name         String        @map("Name")
  album        Album?        @map("AlbumId")
  mediaType    MediaType     @map("MediaTypeId")
  genre        Genre?        @map("GenreId")
  composer     String?       @map("Composer")
  milliseconds Int           @map("Milliseconds")
  bytes        Int           @map("Bytes")
  unitPrice    Float         @map("UnitPrice")
  // relation field not present in DB schema
  invoiveItems InvoiceItem[]

  @@map("tracks")
}
```
It should not need to exist, since it is just a join table. Since it does exist though, prisma2 thinks of it as a real model, and creates an implicit relation to the `Track` model via a field called `playlistTracks`. Note that this is wrong, this field should not exist. What this does then is that the autogenerated script for `Track` model now looks like:
```
photon.tracks.findMany({
  select: {
    ...
    playlistTracks: true
  }
})
```
This fails in the connector, because the database itself has no field called `playlistTrack`. You can reproduce it with photon as well during `prisma2 generate`. The types for the `tracks.findMany` query will have `playlistTrack` as a valid field.

All of this stems from the wrong schema, because of a lack of support from prisma2. I do not believe this is an issue with Studio itself, since the generated query is correct as far as the schema is concerned. Handling this specific case for this specific dataset is obviously not feasible. I've created https://github.com/prisma/prisma2/issues/773, which is the root of the problem.

Since Chinook itself is "not supported", I'm going to remove it from the demo app, but the created issue should help to fix this in the long run. I will also add the IMDB dataset (https://github.com/prisma/prisma-datasets/tree/master/datasets/sqlite/imdb) that suffers from similar problems, but @nikolasburk has changed the underlying SQLite DB's structure to make it all work.

**Comment by schickling** [comment] 2019-10-17 11:38
Thanks a lot for explaining @madebysid. I'd like to keep this issue open until prisma/prisma2#773 is fixed though for visibility. 🙏

**Comment by heymartinadams** [comment] 2019-10-29 16:42
Receiving the same error message `Cannot read property 'map' of undefined` when I try to connect an optional list from the `EventTopic` model to a new record in the `Event` model.

Use `prisma2@2.0.0-preview015`.

![image](https://user-images.githubusercontent.com/11673745/67788502-b2b31b00-fa2f-11e9-8d47-de76577db4ed.png)

Schema:
```graphql
model Event {
  EventTopics EventTopic[]  @relation(name: "OEventsToREventTopics")
}

model EventTopic {
  Events      Event[]       @relation(name: "OEventsToREventTopics")
}
```

**Comment by heymartinadams** [comment] 2019-10-29 16:48
This appears to be happening with every `...-to-many` connection.

**Comment by madebysid** [comment] 2019-10-30 13:59
@heymartinadams I believe your issue is not the same as this one. The trace however is the same as https://github.com/prisma/studio/issues/251, I'll look into it soon. Please follow that issue for updates :)

**Comment by matthewmueller** [comment] 2020-03-02 09:54
I'm unable to reproduce this anymore and #251 should be fixed, so I'll close this.

**Closed by matthewmueller** 2020-03-02 09:54 UTC
Labels: bug/2-confirmed, kind/bug
