### ISSUE TITLE
Incorrect seed data

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#406] opened 2020-04-19 22:03 UTC
1. Prisma2 version (`prisma2 -v`):
```
@prisma/cli          : 2.0.0-alpha.1107
Current platform     : darwin
Query Engine         : query-engine 3e4b3d63c6ebd071717743ed1278e9aff2fb3827 (at /Users/.../node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 3e4b3d63c6ebd071717743ed1278e9aff2fb3827 (at /Users/.../node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 3e4b3d63c6ebd071717743ed1278e9aff2fb3827 (at /Users/.../node_modules/@prisma/cli/introspection-engine-darwin)
```

2. I have the following schema:
```prisma
model Client {
  id               String         @default(uuid()) @id
  createdAt        DateTime       @default(now())
  updatedAt        DateTime       @updatedAt
  clientId         String         @unique
  systemKeys       SystemKey[]    @relation("SystemKeysToRClient")
}

model SystemKey {
  id         String      @default(uuid()) @id
  createdAt  DateTime    @default(now())
  updatedAt  DateTime    @updatedAt
  clientId   String
  client     Client      @relation("SystemKeysToRClient", fields: [clientId], references: [clientId])
  publicKey  String      @unique
  secretKey  String      @unique
}
```

3. When I try to seed the following data:
```js
[
  {
    clientId: 'someClientId',
    name: 'Some Client Name',
    systemKeys: {
      create: [
        {
          publicKey: `pk_${crypto.randomBytes(12).toString('hex')}`,
          secretKey: `sk_${crypto.randomBytes(12).toString('hex')}`,
        }
      ]
    }
  }
].map((data) => prisma.client.create({ data }))
```

4. And then I startup the Prisma Studio, I see the following in the **System Key** table:
`clientId` → `someClientId`
`client` → `Client`
`publicKey` → `someClientId`
`secretKey` → `pk_102cf3465aac0244aaa60fbe`

and when I replace the `references: [clientId]` to `references: [id]` in the **SystemKey** model in the schema file, I get the actual `id` in the `publicKey` field, and (as before) the public key shows up in the `secretKey` field.

And, of course, if I add an extra field to the **SystemKey** model, the actual secret key shows up in that extra field:

`extraField` → `sk_ef193987df9b4d7fdffd4a41`

Strange, huh?

**Comment by heymartinadams** [comment] 2020-04-19 22:08
Aha! When I downgrade back to `2.0.0-beta.2` this error disappears.

**Comment by heymartinadams** [comment] 2020-04-19 22:22
Moved issue here: https://github.com/prisma/prisma/issues/2230

**Comment by madebysid** [comment] 2020-04-20 09:55
@heymartinadams huh, what do you see when you try to fetch this record from a standalone script? Just want to make sure this isn't Studio specific.

**Comment by heymartinadams** [comment] 2020-04-20 15:48
@madebysid How do I fetch this record from a standalone script?

**Comment by madebysid** [comment] 2020-04-20 16:07
Oh I mean, just doing a `findMany()` in a separate script, so maybe something like:

```
import { PrismaClient }  from '@prisma/client'

(async() => {
    const prisma = new PrismaCllent();
    console.log(
        await prisma.Client.findMany(),
        await prisma.SystemKey.findMany(),
    )
})
```

**Comment by heymartinadams** [comment] 2020-04-20 19:28
Using `2.0.0-alpha.1104`, from where things are broken. Doing `findMany()` in a script works flawlessly (while Studio still produces incorrect display); it produces the following result:
```
[
  {
    id: '66416a9e-2029-4614-83e4-f8e747f3598d',
    createdAt: 2020-04-20T19:08:01.208Z,
    updatedAt: 2020-04-20T19:08:01.208Z,
    clientId: 'someClientId',
    name: 'Some Client Name'
  }
] [
  {
    id: '51f1b32d-7b8b-4b29-9efb-4048689eb8d5',
    createdAt: 2020-04-20T19:08:01.208Z,
    updatedAt: 2020-04-20T19:08:01.208Z,
    clientId: 'someClientId',
    publicKey: 'pk_843f1d990341c623719e8f85',
    secretKey: 'sk_55bd6981b582a50717804993'
  }
]
```

```js
import { PrismaClient } from '@prisma/client'
;(async () => {
	const prisma = new PrismaClient()
	const client = await prisma.client.findMany()
	const systemKeys = await prisma.systemKey.findMany()
	console.log(client, systemKeys)
})()
```

## Possible error

I commented out a `boolean` field *in this particular model in the schema* to make Prisma work — I was receiving an unrelated error message. I didn’t include this since I thought it wasn’t relevant. However, please notice its position: its existence seems to push subsequent data further down, leading to a possible display error in Studio.

## Actual schema
```prisma
model Client {
  ...
}

model SystemKey {
  id         String      @default(uuid()) @id
  createdAt  DateTime    @default(now())
  updatedAt  DateTime    @updatedAt
  clientId   String
  client     Client      @relation("SystemKeysToRClient", fields: [clientId], references: [clientId])
  // active     Boolean     @default(true)
  publicKey  String      @unique
  secretKey  String      @unique
}
```

If I uncomment it, and rebuild the entire schema (including seeding with new data and clearing the cache before restarting Studio), I get the following error, below. **This error does not appear with `2.0.0-alpha.1103` and below.**

However, if I either comment out or remove the boolean `active` field, it makes the error go away for `2.0.0-alpha.1104` but produces this display error in Studio.

```
'Error: \n' +
    'Invalid `prisma.systemKey.findMany()` invocation:\n' +
    '\n' +
    'Error occurred during query execution:\n' +
    'ConnectorError(ConnectorError { user_facing_error: None, kind: ConversionError(Custom { kind: InvalidData, error: "Bool value not stored as bool or int" }\n' +
    '\n' +
    '   0: backtrace::backtrace::trace\n' +
    '   1: backtrace::capture::Backtrace::new_unresolved\n' +
    '   2: failure::backtrace::internal::InternalBacktrace::new\n' +
    '   3: <failure::backtrace::Backtrace as core::default::Default>::default\n' +
    '   4: sql_query_connector::row::row_value_to_prisma_value\n' +
    '   5: <quaint::connector::result_set::result_row::ResultRow as sql_query_connector::row::ToSqlRow>::to_sql_row\n' +
    '   6: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '   7: std::future::poll_with_tls_context\n' +
    '   8: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '   9: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  10: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  11: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  12: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  13: std::future::poll_with_tls_context\n' +
    '  14: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  15: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  16: std::panicking::try::do_call\n' +
    '  17: __rust_maybe_catch_panic\n' +
    '  18: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  19: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  20: <std::future::GenFuture<T> as core::future::future::Future>::poll\n' +
    '  21: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch\n' +
    '  22: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll\n' +
    '  23: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll\n' +
    '  24: tokio::task::core::Core<T>::poll\n' +
    '  25: std::panicking::try::do_call\n' +
    '  26: __rust_maybe_catch_panic\n' +
    '  27: tokio::task::harness::Harness<T,S>::poll\n' +
    '  28: tokio::runtime::thread_pool::worker::GenerationGuard::run_task\n' +
    '  29: tokio::runtime::thread_pool::worker::GenerationGuard::run\n' +
    '  30: std::thread::local::LocalKey<T>::with\n' +
    '  31: tokio::runtime::thread_pool::worker::Worker::run\n' +
    '  32: tokio::task::core::Core<T>::poll\n' +
    '  33: std::panicking::try::do_call\n' +
    '  34: __rust_maybe_catch_panic\n' +
    '  35: tokio::task::harness::Harness<T,S>::poll\n' +
    '  36: tokio::runtime::blocking::pool::Inner::run\n' +
    '  37: tokio::runtime::context::enter\n' +
    '  38: std::sys_common::backtrace::__rust_begin_short_backtrace\n' +
    '  39: std::panicking::try::do_call\n' +
    '  40: __rust_maybe_catch_panic\n' +
    '  41: core::ops::function::FnOnce::call_once{{vtable.shim}}\n' +
    '  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n' +
    '  43: std::sys::unix::thread::Thread::new::thread_start\n' +
    '  44: _ZL12preoptimized\n' +
    ') })\n' +
    '    at PrismaClientFetcher.request (/Users/__USER__/.cache/prisma/studio/Users-.../runtime/index.js:1:85730)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:85:5)',
```

**Comment by madebysid** [comment] 2020-04-22 15:42
Hmm, I'm going to look into this, because this looks like it is specific to Studio.

**Comment by joshmeney** [comment] 2020-05-20 05:59
Also running into what I think is a related issue. Tested on both and 2.0.0-beta.5 and 2.0.0-alpha.1228

In Studio, annotated relation fields and their relation scalars seem to overwrite the following field in model with a value of NULL.

For example, using this schema:
```javascript
model Contact {
  id            Int            @default(autoincrement()) @id
  firstName     String?
  lastName      String?
  email         String         @unique
  startup       Startup        @relation(fields: [startupId], references: [id])
  startupId     Int
  validEmail    Boolean        @default(true)
  scoutingFiles ScoutingFile[]
}
```

Upon creating or updating a record in Studio, the validEmail field is overwritten with NULL, resulting in the same "Bool value not stored as bool or int" error mentioned above. The same thing seems to happen for all field types, including other annotated relation fields.

Currently the only workaround is to have the annotated relation/relation scalar as the last field in a model so that there isn't anything to overwrite after it. This however doesn't work if you've got two or more annotated relation/relation scalar fields.

Creating or updating records in with the CLI works perfectly, however the same issue occurs when you try and view them in Studio.

**Comment by madebysid** [comment] 2020-05-20 13:18
@joshmeney Ah thanks for the repro! I'm now almost certain I'm doing something wrong.

So I used your schema (with some changes to make it valid):

```
model Startup {
  id      Int       @id
  name    String
  Contact Contact[]
}

model Contact {
  id         Int     @default(autoincrement()) @id
  firstName  String?
  lastName   String?
  email      String  @unique
  startup    Startup @relation(fields: [startupId], references: [id])
  startupId  Int
  validEmail Boolean @default(true)
  // Got rid of scoutingFIles since that didn't seem relevant. Please correct me if I'm wrong.
}
```
(Let me know if this isn't actually what your schema looks like. If you can, linking to your full schema will be super helpful!)

And then:
1. In order to create a `Contact`, I needed a `Startup`, so I created a `Startup`, with `{ id: 1, name: "Startup 1" }`. Pressed `Save`
2. I switched to the Contact table and created a Contact. I left all values as they were (the defaults), but changed the `startupId` field to `1`.( Consequently, the `startup` field also changed, since they're 2-way bound). Pressed `Save`.

And I see no errors / crashes :(

There's one more thing: there should be a log in the DevTools Console with the query that Studio sent to Prisma Client under the hood to create the record. Could you verify if that query is actually correct? In your case, `validEmail` shouldn't be `null`?

**Comment by joshmeney** [comment] 2020-05-20 23:08
Hey @madebysid, sorry by the lack of details in that last post, I was running out the door. Oddly I just retried and that worked too, so I've modified the schema a little bit to make it reoccur.

- DB created with Migrate
- OS: Windows 10
- Database: Digitalocean managed Postgres 11

Full schema below:
```javascript
enum Source {
  CRUNCHBASE
  ANGELLIST
  LEADSPICKER
  MANUAL
}

enum StartupStatus {
  ALUMNI
  ACTIVE
  JUNK
  NOTINTERESTED
}

enum ScoutingStage {
  APPLIEDFASTTRACK
  APPLIEDPROGRAM
  TOP100
  TOP20
  TOP10
}

model Startup {
  id               Int               @default(autoincrement()) @id
  createdAt        DateTime          @default(now())
  name             String
  startupStatus    StartupStatus
  contacts         Contact[]
  sources          SourceProfile[]
  scoutingFiles    ScoutingFile[]
  relevantPrograms RelevantProgram[]
  cohorts          Cohort[]          @relation(references: [id])
  globalApproved   Boolean           @default(false)
  femaleFounder    Boolean           @default(false)
  city             String?
  country          String?
  region           String?
  domain           String?
}

model Contact {
  id            Int            @default(autoincrement()) @id
  createdAt     DateTime       @default(now())
  firstName     String?
  lastName      String?
  email         String         @unique
  startup       Startup        @relation(fields: [startupId], references: [id])
  startupId     Int
  jobTitle      String
  validEmail    Boolean        @default(true)
  scoutingFiles ScoutingFile[]
}

model RelevantProgram {
  id        Int     @default(autoincrement()) @id
  startup   Startup @relation(fields: [startupId], references: [id])
  startupId Int
  program   Program @relation(fields: [programId], references: [id])
  programId Int
  relevant  Boolean @default(false)
}

model Program {
  id               Int               @default(autoincrement()) @id
  name             String            @unique
  abbr             String
  Cohort           Cohort[]
  relevantPrograms RelevantProgram[]
}

model Cohort {
  id            Int            @default(autoincrement()) @id
  name          String         @unique
  year          Int
  program       Program        @relation(fields: [programId], references: [id])
  programId     Int
  startups      Startup[]      @relation(references: [id])
  scoutingFiles ScoutingFile[]
}

model ScoutingFile {
  id                 Int           @default(autoincrement()) @id
  scoutingStage      ScoutingStage
  description        String?
  biggestAchievement String?
  presentation       String?
  employeeCount      Int?
  founded            Int?
  businessStage      String?
  themes             String[]
  revenueModel       String[]
  fundingType        String[]
  founders           String[]
  referral           String?
  startup            Startup       @relation(fields: [startupId], references: [id])
  startupId          Int
  cohort             Cohort        @relation(fields: [cohortId], references: [id])
  cohortId           Int
  primaryContact     Contact       @relation(fields: [primaryContactId], references: [id])
  primaryContactId   Int
}

model SourceProfile {
  id              Int      @default(autoincrement()) @id
  source          Source
  url             String   @unique
  startup         Startup  @relation(fields: [startupId], references: [id])
  startupId       Int
  city            String?
  country         String?
  region          String?
  description     String?
  founded         Int?
  tags            String[]
  businessStage   String?
  employeeCount   String?
  fundingStage    String?
  fundingCurrency String?
  fundingAmount   Int?
  founders        String?
  email           String?
  website         String?
  linkedIn        String?
  twittter        String?
  facebook        String?
  searchCategory  String[]
  searchKeyword   String[]
}
```

So steps to reproduce are:
1. Create a `Startup` in Startup table with `{ id: 1, name: "Startup 1" }`
2. Switch to Contact table and create a 'Contact` with an `email` of `"ceo@gmail.com"`, `jobTitle`of `"CEO"` and link it to `"Startup 1"` by changing the `startupId` to `1`.
3. This throws the error `Bool value not stored as bool or int`. I'm not sure why this is now skipping over the `jobTitle` as I believe this schema format previously threw an error complaining about `jobTitle` either being NULL or receiving an Int.

The query in the console log looks fine though. See console log and error message belows

Looking at that schema, I would also encounter errors in the following situations:
- Creating a `RelevantProgram` results in `PANIC: Application logic invariant error: received null value for field program which may not be null`
- I can't create a `ScoutingFile` record as I haven't created a `Contact` yet. However if I did create a `Contact` through the CLI instead, then trying to create a `ScoutingFile` would result in `PANIC: Application logic invariant error: received null value for field cohort which may not be null`

```
Sending request to prisma client:  prisma.contact.create(
{
  "data": {
    "firstName": null,
    "lastName": null,
    "email": "ceo@gmail.com",
    "startup": {
      "connect": {
        "id": 1
      }
    },
    "jobTitle": "CEO",
    "validEmail": true
  },
  "select": {
    "id": true,
    "createdAt": true,
    "firstName": true,
    "lastName": true,
    "email": true,
    "startup": true,
    "startupId": true,
    "jobTitle": true,
    "validEmail": true,
    "scoutingFiles": true
  }
}
)
```

```
Error in Prisma Client request:

Error:
Invalid `prisma.contact.create()` invocation:

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConversionError(Custom { kind: InvalidData, error: "Bool value not stored as bool or int" }

0: backtrace::backtrace::trace
1: backtrace::capture::Backtrace::new_unresolved
2: failure::backtrace::internal::InternalBacktrace::new
3: <failure::backtrace::Backtrace as core::default::Default>::default
4: sql_query_connector::row::row_value_to_prisma_value
5: <quaint::connector::result_set::result_row::ResultRow as sql_query_connector::row::ToSqlRow>::to_sql_row
6: <std::future::GenFuture<T> as core::future::future::Future>::poll
7: <std::future::GenFuture<T> as core::future::future::Future>::poll
8: std::future::poll_with_tls_context
9: <std::future::GenFuture<T> as core::future::future::Future>::poll
10: <std::future::GenFuture<T> as core::future::future::Future>::poll
11: <std::future::GenFuture<T> as core::future::future::Future>::poll
12: <std::future::GenFuture<T> as core::future::future::Future>::poll
13: <std::future::GenFuture<T> as core::future::future::Future>::poll
14: <std::future::GenFuture<T> as core::future::future::Future>::poll
15: <std::future::GenFuture<T> as core::future::future::Future>::poll
16: <std::future::GenFuture<T> as core::future::future::Future>::poll
17: <std::future::GenFuture<T> as core::future::future::Future>::poll
18: <std::future::GenFuture<T> as core::future::future::Future>::poll
19: <std::future::GenFuture<T> as core::future::future::Future>::poll
20: std::future::poll_with_tls_context
21: <std::future::GenFuture<T> as core::future::future::Future>::poll
22: <std::future::GenFuture<T> as core::future::future::Future>::poll
23: std::panicking::try::do_call
24: __rust_maybe_catch_panic
at src\libpanic_unwind/lib.rs:86
25: std::future::poll_with_tls_context
26: <std::future::GenFuture<T> as core::future::future::Future>::poll
27: <std::future::GenFuture<T> as core::future::future::Future>::poll
28: <std::future::GenFuture<T> as core::future::future::Future>::poll
29: <hyper::proto::h2::server::H2Stream<F,B> as core::future::future::Future>::poll
30: tokio::task::core::Core<T>::poll
31: std::panicking::try::do_call
32: __rust_maybe_catch_panic
at src\libpanic_unwind/lib.rs:86
33: tokio::task::harness::Harness<T,S>::poll
34: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
35: tokio::runtime::thread_pool::worker::GenerationGuard::run
36: std::thread::local::LocalKey<T>::with
37: tokio::runtime::thread_pool::worker::Worker::run
38: tokio::task::core::Core<T>::poll
39: std::panicking::try::do_call
40: __rust_maybe_catch_panic
at src\libpanic_unwind/lib.rs:86
41: tokio::task::harness::Harness<T,S>::poll
42: tokio::runtime::blocking::pool::Inner::run
43: tokio::runtime::context::enter
44: std::sys_common::backtrace::__rust_begin_short_backtrace
45: std::panicking::try::do_call
46: __rust_maybe_catch_panic
at src\libpanic_unwind/lib.rs:86
47: core::ops::function::FnOnce::call_once{{vtable.shim}}
48: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\liballoc/boxed.rs:1017
49: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\liballoc/boxed.rs:1017
std::sys_common::thread::start_thread
at src\libstd\sys_common/thread.rs:13
std::sys::windows::thread::Thread::new::thread_start
at src\libstd\sys\windows/thread.rs:51
50: sqlite3GenerateConstraintChecks
51: sqlite3GenerateConstraintChecks
) })
at PrismaClientFetcher.request (C:\Users\Josh\AppData\Roaming\Prisma\Studio\-Users-Josh-Local Sites-sbc-dodb\runtime\index.js:1:83312)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async eval (eval at Photon.request (C:\Users\Josh\Local Sites\sbc\dodb\node_modules\@prisma\cli\build\index.js:2:1430036), <anonymous>:5:32)
at async Photon.request (C:\Users\Josh\Local Sites\sbc\dodb\node_modules\@prisma\cli\build\index.js:2:1430030)
at async PhotonService.respond (C:\Users\Josh\Local Sites\sbc\dodb\node_modules\@prisma\cli\build\index.js:2:2076519)
at async WebSocket.StudioServer.onWSMessage (C:\Users\Josh\Local Sites\sbc\dodb\node_modules\@prisma\cli\build\index.js:2:710064)
```

**Comment by madebysid** [comment] 2020-05-27 10:59
@joshmeney Sorry for not responding, but I did see your comment earlier. There have been a couple of fixes on Prisma Client on alpha (https://github.com/prisma/prisma/issues/2442, https://github.com/prisma/prisma/issues/2501 & https://github.com/prisma/prisma/issues/2525) that address problems similar to yours. I'm also unable to reproduce your issue any more.

Could you try updating @prisma/cli & @prisma/client to the latest alpha (2.0.0-alpha.1253 as of writing) and check if this is fixed now? If not, let me know, and I'll dig deeper!

**Comment by joshmeney** [comment] 2020-05-28 04:50
@madebysid no worries, wasn't urgent for me.

Updated to the latest alpha (2.0.0-alpha.1257) and everything is now working fine.

Thanks for letting me know!

**Closed** 2020-05-28 09:15 UTC
Labels: bug/1-repro-available, kind/bug
