### ISSUE TITLE
Prisma studio O2M relations loads all related values into memory

### ISSUE THREAD

**Issue by FLevent29** [prisma/studio#967] opened 2022-06-21 12:28 UTC
**Describe the bug**
When there is a O2M relationship with 10s of thousands of related records, Prisma studio loads all or anyways does a lot more work than it's necessary to a point of critical fault. It fills up my memory completely to the point that Firefox almost crashes.

Also it seems to do the same with M2M relationships, except Prisma client straight up errs in that situation with a message among the lines "make sure database is running on ...".

**To Reproduce**
1. Create a O2M or M2M relationship between two models, and add at least 100000 of preferably fairly big records in the model which has the reference `id` to the other model and add at least a few records in the other model as well. For M2M works whichever way, just make sure there are plenty of records at least on one side.
2. Start `prisma studio`
3. Select the model which has the fewer records connecting to 10s of thousands of records in the other model.
4. Wait for quite a bit for those few ( could be 1 to 5 ) records to barely load up and fill up your memory quite quickly with gigabytes worth of data.

**Expected behavior**
I expect for studio to only count a record's related records, like `findUnique({ where: { id }, include: { _count: { relatedModel: true } } })`, or whatever way it would make more sense. Currently in the error message I get from M2M in this same situation shows me that it's more like `findMany({ ..., select: { fieldA: true, fieldB: true, ... , relatedModel: true } })`, which if I'm not mistaken gets all of the `relatedModel` records and all their fields.

**Screenshots**
![Screenshot 2022-06-21 150013](https://user-images.githubusercontent.com/55688616/174797972-f37f7cbe-8403-4aa7-a0ea-14df157ae470.jpg)
![Screenshot 2022-06-21 150039](https://user-images.githubusercontent.com/55688616/174798004-d0820e73-a394-4a98-a162-ee5384cfc3e0.jpg)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Pro
 - Browser: Mozilla Firefox 101.0.1 (64-bit)
 - Version: Prisma 3.15.2

**Comment by petradonka** [comment] 2022-06-21 15:39
Thank you for the detailed description! 👌 

I think this is a duplicate of https://github.com/prisma/studio/issues/751. We have this on our radar and would like to generally improve performance especially for large DBs, but don't have a timeline right now.

**Closed** 2022-06-21 15:40 UTC
Labels: topic: Prisma CLI

**Comment by FLevent29** [comment] 2022-06-21 17:18
Sorry, didn't search long enough for similar issues. Thanks for the quick reply though!
