### ISSUE TITLE
"null" as a string the default empty value of required string fields

### ISSUE THREAD

**Issue by matthewmueller** [prisma/studio#456] opened 2020-07-06 10:45 UTC
Possible solutions:

- Default to an empty string
- Show red that it's an invalid value

![CleanShot 2020-07-06 at 12 44 14](https://user-images.githubusercontent.com/170299/86585251-6e94f480-bf86-11ea-98c3-3eeec179b21e.gif)

**Comment by madebysid** [comment] 2020-07-06 11:56
@matthewmueller This is a regression. For required fields, the "cleared" value is supposed to be an empty string (since it is more common to want to do that)

**Comment by madebysid** [comment] 2020-07-06 22:33
fixed on latest `dev`

**Closed by madebysid** 2020-07-06 22:33 UTC
Labels: bug/2-confirmed, kind/bug
