### ISSUE TITLE
Prisma Studio cache querying old, non-existent model?

### ISSUE THREAD

**Issue by heymartinadams** [prisma/studio#405] opened 2020-04-19 19:44 UTC
1. Prisma2 version:
```
@prisma/cli          : 2.0.0-beta.2
Current platform     : darwin
Query Engine         : query-engine 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/.../node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/.../node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/.../node_modules/@prisma/cli/introspection-engine-darwin)
```

2. Logs from Developer Tools Console, if any:
![image](https://user-images.githubusercontent.com/11673745/79697846-eda54700-8239-11ea-95e6-29d52101bd07.png)

3. Does the issue persist even after updating to the latest `prisma2` alpha (`npm i -g prisma2@alpha`)?

Yes. Btw, you may need to update this instruction to `npm -i @prisma/client && npm -i @prisma/cli@alpha --dev`

4. Error:
I deleted the `ParticpantInvitee` model and replaced it with an `Invitee` model. Replaced ALL references to `ParticipantInvitee` with `Invitee` throughout the entire app (including all casing variations). Then deleted all migrations and even the SQLite db and `node_modules` folder. After re-installing node_modules did a fresh `npx prisma generate` before doing `npx prisma studio --experimental` and still getting the error that Prisma is querying `prisma.participantInvitee.count()`. This even happens after upgrading the `@prisma/client` and `@prisma/cli` to latest alpha.

**Comment by heymartinadams** [comment] 2020-04-19 19:50
I see there’a a cache at `/Users/__USER__/.cache/prisma/studio/` After deleting it, appears to work.

**Comment by osirvent** [comment] 2020-04-20 12:59
Only deleting the cache didn't work for me. A `prisma generate` was also needed.

**Comment by madebysid** [comment] 2020-04-23 09:02
@heymartinadams @osirvent I've just pushed out a new alpha (2.0.0-alpha.1126) where I've made some changes that should address this. Could you guys update and let me know if this is still happening?

**Comment by madebysid** [comment] 2020-04-27 08:44
Closing this, but please do let me know if this is still an issue and I'll reopen and re-investigate!

**Closed by madebysid** 2020-04-27 08:44 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by heymartinadams** [comment] 2020-04-27 15:58
Thanks, @madebysid. Upgraded to latest beta, but haven’t re-encountered this issue (though I also didn’t attempt to re-create the issue.)

**Comment by BillyGoatsOats** [comment] 2020-05-18 18:34
I feel like this issue still exists in the latest beta version of studio, and it is related to the cache in `/Users/__USER__/.cache/prisma/studio/` but deleting it manually can cause some issues where I have to reinstall everything.

**Comment by BillyGoatsOats** [comment] 2020-05-18 18:39
Is there a command that can be added that will properly clear the cached `/Users/__USER__/.cache/prisma/studio/` I will encounter this bug even if I delete `node_modules`

**Comment by madebysid** [comment] 2020-05-18 19:31
@BillyGoatsOats The only thing in Studio's cache is a generated Prisma Client that it uses internally, so it should be okay to delete it like you did.

The error that you've quoted seems to be coming from Studio's internal Prisma Client. Just so I'm 100% sure, have you migrated your DB after changing your schema? The error makes it look like these columns do not exist in your database.

In the likely scenario that you have migrated: Studio logs every query it sends out in the DevTools Console. Could you perhaps try the failing query in a standalone script and see if that crashes in the same wa too?

Your script might look something like:
```
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const main = async () => {
  const users = await prisma.user.findMany(); // Replace this with the query you found in DevTools
  console.log(users);
}

main()
  .catch(e => console.log(e))
  .finally(() => prisma.disconnect());
```
(In your specific case, you might also be able to stick the query in one of your resolvers)

In case you're still having problems, could you share your schema & the failing query here? I can try and reproduce this too in that case!

**Comment by BillyGoatsOats** [comment] 2020-05-19 01:01
@madebysid Thanks for the quick reply, I was actually able to work past this particular issue with Prisma Studio by updating to `"@prisma/cli": "2.0.0-beta.5"`, clearing migrations and re-migrating and seeding my Postgres DB (Heroku). I am actually now encountering a different issue in Studio showing this error:
![image](https://user-images.githubusercontent.com/60484013/82272935-45b69280-9939-11ea-9b53-dc93d01208f9.png)
It seems to be happen when I toggle certain fields, despite them showing data proper in the table view
```[runQuery] Error in Prisma Client request: 

Error: 
Invalid `prisma.match.findMany()` invocation:

Attempted to serialize scalar '1' with incompatible type 'String'
    at PrismaClientFetcher.request (/Users/willgeller/.cache/prisma/studio/Users-willgeller-wills-repos-DropShot-dropshot-prisma2/runtime/index.js:1:86104)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
{…}
​
code: "prisma.match.findMany({\n  first: 100,\n  select: {\n    id: true,\n    createdAt: true,\n    updatedAt: true,\n    matchTime: true,\n    matchScore: true,\n    incomplete: true,\n    winnerId: true,\n    loserId: true,\n    leagueId: true,\n    league: true,\n    location: true,\n    note: true,\n  }\n})"
​
error: Object { telemetry: true, message: "\nInvalid `prisma.match.findMany()` invocation:\n\nAttempted to serialize scalar '1' with incompatible type 'String'", stack: "Error: \nInvalid `prisma.match.findMany()` invocation:\n\nAttempted to serialize scalar '1' with incompatible type 'String'\n    at PrismaClientFetcher.request (/Users/willgeller/.cache/prisma/studio/Users-willgeller-wills-repos-DropShot-dropshot-prisma2/runtime/index.js:1:86104)\n    at process._tickCallback (internal/process/next_tick.js:68:7)" }```

I can consistently get `Attempted to serialize scalar '1' with incompatible type 'String'` or Attempted to serialize scalar '3' with incompatible type 'String' when enabling the filters. Data seems to be returning fine in my GraphQL playground though. happy to open a new git issue if that's more ideal.

**Comment by BillyGoatsOats** [comment] 2020-05-19 01:14
Strangely enough it seems to be when enable certain combinations of filters such as turning on `leagueId` and `Location` at the same time, it seems to get mixed up. Also here is my Prisma 2 model for reference:
![image](https://user-images.githubusercontent.com/60484013/82273829-c24a7080-993b-11ea-992c-2925127140bc.png)

**Comment by madebysid** [comment] 2020-05-19 08:25
Ah, that's a Prisma Client bug that a lot of people have been seeing recently: https://github.com/prisma/prisma/issues/2442 & https://github.com/prisma/prisma/issues/2501. I'll talk to the Client team and try to get this fixed as soon as they can. Best follow those threads for updates! Once they're fixed, I'll bump up internal versions and release a new version of Studio!

**Comment by pbitkowski** [comment] 2022-02-24 07:33
I had the same issue, removed node_modules, forced yarn to remove any cache. Then it was prisma studio app on mac that was caching old model. Removed this from Mac and now it works correctly. 

Version of the prisma: 3.10.0
